<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart4Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'mn',
                'nama_negara' => 'Mongolia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Mongolia',
                'nama_kedutaan_besar_en' => 'Embassy of Mongolia',
                'format_undangan' => 'Ambassador of Mongolia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Enkhtaivan Dashnyam Uyangatsetseg Ulzii-ochir',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Imperium Lt. 12, Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Guntur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12980',
                'website' => null,
                'latitude' => -6.2104,
                'longitude' => 106.8306,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mz',
                'nama_negara' => 'Mozambik',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Mozambik',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Mozambique',
                'format_undangan' => 'Ambassador of the Republic of Mozambique to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. António Rodrigues José',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Tengah Blok C4 No. 30',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2276,
                'longitude' => 106.8298,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mm',
                'nama_negara' => 'Myanmar',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Myanmar',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of the Union of Myanmar',
                'format_undangan' => 'Ambassador of the Republic of the Union of Myanmar to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. U Mang Hau Thang',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. A. R. Salim No. 109',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1965,
                'longitude' => 106.8262,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ng',
                'nama_negara' => 'Nigeria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Nigeria',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Nigeria',
                'format_undangan' => 'Ambassador of the Federal Republic of Nigeria to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Eze Nduka Thomas',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Denpasar Raya No. 34, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2281,
                'longitude' => 106.8328,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'no',
                'nama_negara' => 'Norwegia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Norwegia',
                'nama_kedutaan_besar_en' => 'Royal Norwegian Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Norway to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Rut Krüger Giverin',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 20, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'om',
                'nama_negara' => 'Oman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kesultanan Oman',
                'nama_kedutaan_besar_en' => 'Embassy of the Sultanate of Oman',
                'format_undangan' => 'Ambassador of the Sultanate of Oman to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sheikh Mohamad Ahmed Salim Al-Shanfari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat I No. 7',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2274,
                'longitude' => 106.8239,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pk',
                'nama_negara' => 'Pakistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Pakistan',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Pakistan',
                'format_undangan' => 'Ambassador of the Islamic Republic of Pakistan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Zahid Hafeez Chaudhri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat Blok E.3.9 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2281,
                'longitude' => 106.8238,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ps',
                'nama_negara' => 'Palestina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Palestina',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Palestine',
                'format_undangan' => 'Ambassador of the State of Palestine to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdalfatah Ahmed Khalil Alsattari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Sisingamangaraja No. 8',
                'kelurahan' => 'Selong',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12110',
                'website' => null,
                'latitude' => -6.2372,
                'longitude' => 106.7989,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pa',
                'nama_negara' => 'Panama',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Panama',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Panama',
                'format_undangan' => 'Ambassador of the Republic of Panama to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Alejandro Arturo Silvera Castillo',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Center 5 Lt. 13, Jl. Jend. Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2161,
                'longitude' => 106.8185,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pg',
                'nama_negara' => 'Papua Nugini',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Papua Nugini',
                'nama_kedutaan_besar_en' => 'Embassy of the Independent State of Papua New Guinea',
                'format_undangan' => 'Ambassador of the Independent State of Papua New Guinea to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Simon Namis',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Wisma Standard Chartered Bank Lt. 16, Jl. Jend. Sudirman Kav. 33A',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.2082,
                'longitude' => 106.8196,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'fr',
                'nama_negara' => 'Perancis',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Perancis',
                'nama_kedutaan_besar_en' => 'Embassy of France',
                'format_undangan' => 'Ambassador of France to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Fabien Laurent Robert Penone',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M.H. Thamrin No. 20',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1908,
                'longitude' => 106.8239,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ae',
                'nama_negara' => 'Persatuan Emirat Arab',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Persatuan Emirat Arab',
                'nama_kedutaan_besar_en' => 'Embassy of the United Arab Emirates',
                'format_undangan' => 'Ambassador of the United Arab Emirates to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdulla Salem Obaid Salem Aldhaheri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Prof. Dr. Satrio No. C-8, Kuningan',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2233,
                'longitude' => 106.8261,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pe',
                'nama_negara' => 'Peru',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Peru',
                'nama_kedutaan_besar_en' => 'Embassy of Peru',
                'format_undangan' => 'Ambassador of Peru to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Luis Raúl Tsuboyama Galván',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Imperium Lt. 16, Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Guntur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12980',
                'website' => null,
                'latitude' => -6.2104,
                'longitude' => 106.8306,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pl',
                'nama_negara' => 'Polandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Polandia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Poland',
                'format_undangan' => 'Ambassador of the Republic of Poland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Barbara Magda Szymanowska',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-1 No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2312,
                'longitude' => 106.8326,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pt',
                'nama_negara' => 'Portugal',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Portugal',
                'nama_kedutaan_besar_en' => 'Embassy of Portugal',
                'format_undangan' => 'Ambassador of Portugal to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Ms. Maria Gabriela Vieira Soares de Albergaria',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Indramayu No. 2A',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1985,
                'longitude' => 106.8298,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'qa',
                'nama_negara' => 'Qatar',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Qatar',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Qatar',
                'format_undangan' => 'Ambassador of the State of Qatar to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Sultan bin Mubarak Saad Al-Dosari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung No. 5',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2291,
                'longitude' => 106.8285,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cn',
                'nama_negara' => 'Republik Rakyat Tiongkok',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rakyat Tiongkok',
                'nama_kedutaan_besar_en' => 'Embassy of the People\'s Republic of China',
                'format_undangan' => 'Ambassador of the People\'s Republic of China to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Wang Lutong',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan No. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2282,
                'longitude' => 106.8262,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ro',
                'nama_negara' => 'Rumania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Rumania',
                'nama_kedutaan_besar_en' => 'Embassy of Romania',
                'format_undangan' => 'Ambassador of Romania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Dan Adrian Bălănescu',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Cik Ditiro No. 42A',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1978,
                'longitude' => 106.8361,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ru',
                'nama_negara' => 'Rusia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Federasi Rusia',
                'nama_kedutaan_besar_en' => 'Embassy of the Russian Federation',
                'format_undangan' => 'Ambassador of the Russian Federation to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sergei Gennadievich Tolchenov',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-7 No. 1-2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2201,
                'longitude' => 106.8322,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'rw',
                'nama_negara' => 'Rwanda',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rwanda',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Rwanda',
                'format_undangan' => 'Ambassador of the Republic of Rwanda to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sheikh Abdul Karim Harelimana',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara BTPN Lt. 31, Jl. DR. Ide Anak Agung Gde Agung',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2298,
                'longitude' => 106.8272,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
