<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart3Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'kh',
                'nama_negara' => 'Kamboja',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kamboja',
                'nama_kedutaan_besar_en' => 'Royal Embassy of Cambodia',
                'format_undangan' => 'Ambassador of the Kingdom of Cambodia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Tean Samnang',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Tmn Kebon Sirih III No. 4',
                'kelurahan' => 'Kampung Bali',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10250',
                'website' => null,
                'latitude' => -6.1843,
                'longitude' => 106.8188,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ca',
                'nama_negara' => 'Kanada',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kanada',
                'nama_kedutaan_besar_en' => 'Embassy of Canada',
                'format_undangan' => 'Ambassador of Canada to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Jess Dutton',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Center I Lt. 6, Jl. Jend. Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2157,
                'longitude' => 106.8188,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kz',
                'nama_negara' => 'Kazakhstan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kazakhstan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Kazakhstan',
                'format_undangan' => 'Ambassador of the Republic of Kazakhstan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Serzhan Abdykarimov',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. B-12',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2165,
                'longitude' => 106.8302,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ke',
                'nama_negara' => 'Kenya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kenya',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Kenya',
                'format_undangan' => 'Ambassador of the Republic of Kenya to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdirashid Salat Abdille',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung Kav. E.1.2 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2287,
                'longitude' => 106.8278,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sb',
                'nama_negara' => 'Kepulauan Solomon',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kepulauan Solomon',
                'nama_kedutaan_besar_en' => 'Embassy of the Solomon Islands',
                'format_undangan' => 'Ambassador of the Solomon Islands to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Gladys Kamia Isihanua',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'ANZ Tower Lt. 23, Jl. Jend. Sudirman Kav. 33A',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.2082,
                'longitude' => 106.8196,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'co',
                'nama_negara' => 'Kolombia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kolombia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Colombia',
                'format_undangan' => 'Ambassador of the Republic of Colombia to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Carlos Alberto Dueñas Morales',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara BCA Lt. 48, Jl. M.H. Thamrin No. 1',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.195,
                'longitude' => 106.8228,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kr',
                'nama_negara' => 'Korea Selatan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Korea',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Korea',
                'format_undangan' => 'Ambassador of the Republic of Korea to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Yoon Soon-gu',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 58',
                'kelurahan' => 'Kuningan Barat',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12710',
                'website' => null,
                'latitude' => -6.2368,
                'longitude' => 106.8291,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kp',
                'nama_negara' => 'Korea Utara',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rakyat Demokratik Korea',
                'nama_kedutaan_besar_en' => 'Embassy of the Democratic People\'s Republic of Korea',
                'format_undangan' => 'Ambassador of the Democratic People\'s Republic of Korea to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. So Kwang Yun',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 72',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1988,
                'longitude' => 106.8332,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cr',
                'nama_negara' => 'Kosta Rika',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kosta Rika',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Costa Rica',
                'format_undangan' => 'Ambassador of the Republic of Costa Rica to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Francisco José Masís Holdridge',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 12, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'hr',
                'nama_negara' => 'Kroasia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kroasia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Croatia',
                'format_undangan' => 'Ambassador of the Republic of Croatia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Nebojša Koharović',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 21, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cu',
                'nama_negara' => 'Kuba',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kuba',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Cuba',
                'format_undangan' => 'Ambassador of the Republic of Cuba to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Dagmar González Grau',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Sutan Syahrir No. 27',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1891,
                'longitude' => 106.8335,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kw',
                'nama_negara' => 'Kuwait',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kuwait',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Kuwait',
                'format_undangan' => 'Ambassador of the State of Kuwait to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Khalid Jassim E Al Yassin',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat III No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2288,
                'longitude' => 106.8232,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'la',
                'nama_negara' => 'Laos',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Laos',
                'nama_kedutaan_besar_en' => 'Embassy of the Lao People\'s Democratic Republic',
                'format_undangan' => 'Ambassador of the Lao People\'s Democratic Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Khamfeuang Phanthaxay',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan XIV No. 1A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2395,
                'longitude' => 106.8368,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'lb',
                'nama_negara' => 'Lebanon',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Lebanon',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Lebanon',
                'format_undangan' => 'Ambassador of the Republic of Lebanon to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Salam Al Achkar',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Imperium Lt. 27, Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Guntur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12980',
                'website' => null,
                'latitude' => -6.2104,
                'longitude' => 106.8306,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ly',
                'nama_negara' => 'Libya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Libya',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Libya',
                'format_undangan' => 'Ambassador of the State of Libya to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Zakarya MM El Maghrabi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-7 No. 4',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2215,
                'longitude' => 106.8322,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'my',
                'nama_negara' => 'Malaysia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Malaysia',
                'nama_kedutaan_besar_en' => 'Embassy of Malaysia',
                'format_undangan' => 'Ambassador of Malaysia to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Farzamie Sarkawi',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-6 No. 1-3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2241,
                'longitude' => 106.8324,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ma',
                'nama_negara' => 'Maroko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Maroko',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Morocco',
                'format_undangan' => 'Ambassador of the Kingdom of Morocco to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Redouane Houssain',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Denpasar Raya No. 1, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2269,
                'longitude' => 106.8319,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mr',
                'nama_negara' => 'Mauritania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Mauritania',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Mauritania',
                'format_undangan' => 'Ambassador of the Islamic Republic of Mauritania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Weddady Ould Sidi Haiba',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 33',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2279,
                'longitude' => 106.8295,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mx',
                'nama_negara' => 'Meksiko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Meksiko',
                'nama_kedutaan_besar_en' => 'Embassy of Mexico',
                'format_undangan' => 'Ambassador of Mexico to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Francisco De La Torre Galindo',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Mulia Lt. 23, Jl. Jend. Gatot Subroto Kav. 9-11',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.2307,
                'longitude' => 106.8182,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'eg',
                'nama_negara' => 'Mesir',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Arab Mesir',
                'nama_kedutaan_besar_en' => 'Embassy of the Arab Republic of Egypt',
                'format_undangan' => 'Ambassador of the Arab Republic of Egypt to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Yasser Hassan Farag Elshemy',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 68',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1982,
                'longitude' => 106.8331,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
