<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart4Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'ge',
                'nama_negara' => 'Georgia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Georgia',
                'nama_kedutaan_besar_en' => 'Embassy of Georgia',
                'format_undangan' => 'Ambassador of Georgia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Tornike Nozadze',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta.emb@mfa.gov.ge',
                'telepon_kantor' => '021-2941-0842',
                'alamat' => 'Jl. Denpasar Barat Blok C6 No. 19A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://indonesia.mfa.gov.ge/',
                'latitude' => -6.226537,
                'longitude' => 106.828185,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gt',
                'nama_negara' => 'Guatemala',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Guatemala',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Guatemala',
                'format_undangan' => 'Ambassador of the Republic of Guatemala to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Manuel Estuardo Roldán Barillas',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'embindonesia@minex.gob.gt, embaguateindonesia@gmail.com',
                'telepon_kantor' => '021-521-1077, 021-521-1078',
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 11)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227126,
                'longitude' => 106.826364,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'hu',
                'nama_negara' => 'Hungaria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Hungaria',
                'nama_kedutaan_besar_en' => 'Embassy of Hungary',
                'format_undangan' => 'Ambassador of Hungary to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Ms. Lilla Karsay',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'mission.jkt@mfa.gov.hu, indsec1huemb@telkom.net',
                'telepon_kantor' => '021-520-3459, 021-520-3460',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-3 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://jakarta.mfa.gov.hu/eng',
                'latitude' => -6.235327,
                'longitude' => 106.827384,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'in',
                'nama_negara' => 'India',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar India',
                'nama_kedutaan_besar_en' => 'Embassy of India',
                'format_undangan' => 'Ambassador of India to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sandeep Chakravorty',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'info.jakarta@mea.gov.in, admn.jakarta@mea.gov.in, amb.jakarta@mea.gov.in, amboff.india.jakarta@gmail.com',
                'telepon_kantor' => '021-252-2299',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. C22 (Gama Tower)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => 'https://www.indianembassyjakarta.gov.in/',
                'latitude' => -6.223951,
                'longitude' => 106.833731,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'iq',
                'nama_negara' => 'Irak',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Irak',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Iraq',
                'format_undangan' => 'Ambassador of the Republic of Iraq to the Republic of Indonesia',
                'nama_diplomat' => 'Dr. Ammar Hameed Saadallah Al-Khalidy',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => 'iraqembi@rad.net.id',
                'telepon_kantor' => '021-390-4067, 021-390-4068, 021-390-4069',
                'alamat' => 'Jl. Teuku Umar No. 8',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => 'https://mofa.gov.iq/jakarta/',
                'latitude' => -6.192524,
                'longitude' => 106.832852,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ir',
                'nama_negara' => 'Iran',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Iran',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Iran',
                'format_undangan' => 'Ambassador of the Islamic Republic of Iran to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mohammad Boroujerdi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'iranembassy.jakarta@gmail.com, iranemb.jkt@mfa.gov.ir',
                'telepon_kantor' => '021-3193-1378, 021-3193-1391, 021-3193-4637',
                'alamat' => 'Jl. H.O.S. Cokroaminoto No. 110',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://indonesia.mfa.gov.ir/',
                'latitude' => -6.200494,
                'longitude' => 106.827794,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ie',
                'nama_negara' => 'Irlandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Irlandia',
                'nama_kedutaan_besar_en' => 'Embassy of Ireland',
                'format_undangan' => 'Ambassador of Ireland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Sharon Ann Lennon',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakartaem@dfa.ie, juni.triani@dfa.ie',
                'telepon_kantor' => '021-2809-4300',
                'alamat' => 'Jl. Jenderal Sudirman Kav. 29-31 (World Trade Center 1 Lt. 14)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => 'https://www.dfa.ie/irish-embassy/indonesia/',
                'latitude' => -6.215211,
                'longitude' => 106.820414,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'it',
                'nama_negara' => 'Italia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Italia',
                'nama_kedutaan_besar_en' => 'Embassy of Italy',
                'format_undangan' => 'Ambassador of Italy to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Roberto Colaminè',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'ambasciata.jakarta@esteri.it, jakarta.segreteria@esteri.it, consolare.jakarta@esteri.it, visa.jakarta@esteri.it',
                'telepon_kantor' => '021-3193-7445, 021-3193-7440, 021-390-2451',
                'alamat' => 'Jl. Pangeran Diponegoro No. 45',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://ambjakarta.esteri.it/it/',
                'latitude' => -6.201139,
                'longitude' => 106.839777,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'jp',
                'nama_negara' => 'Jepang',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Jepang',
                'nama_kedutaan_besar_en' => 'Embassy of Japan',
                'format_undangan' => 'Ambassador of Japan to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Myochin Mitsuru',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => 'yanti@dj.mofa.go.jp, historina@dj.mofa.go.jp',
                'telepon_kantor' => '021-3192-4308, 021-315-7149',
                'alamat' => 'Jl. M.H. Thamrin No. 24',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => 'https://www.id.emb-japan.go.jp/',
                'latitude' => -6.191791,
                'longitude' => 106.822623,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'de',
                'nama_negara' => 'Jerman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Jerman',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Germany',
                'format_undangan' => 'Ambassador of the Federal Republic of Germany to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ralf Beste',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'info@jakarta.diplo.de, l-vz1@jaka.auswaertiges-amt.de, info@jaka.diplo.de, wi-s1@jaka.diplo.de, konsulat@jaka.diplo.de',
                'telepon_kantor' => '021-3985-5000, 021-3985-5144',
                'alamat' => 'Jl. M.H. Thamrin No. 1',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://jakarta.diplo.de/id-en',
                'latitude' => -6.196844,
                'longitude' => 106.823309,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
