<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart10Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'sy',
                'nama_negara' => 'Suriah',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Arab Suriah',
                'nama_kedutaan_besar_en' => 'Embassy of the Syrian Arab Republic',
                'format_undangan' => 'Ambassador of the Syrian Arab Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdulmonem Annan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem I No. 8, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227145,
                'longitude' => 106.830990,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sr',
                'nama_negara' => 'Suriname',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Suriname',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Suriname',
                'format_undangan' => 'Ambassador of the Republic of Suriname to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Erick Rahmat Moertabat',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Dharmawangsa VIII No. 16',
                'kelurahan' => 'Pulo',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12160',
                'website' => null,
                'latitude' => -6.252816,
                'longitude' => 106.806543,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'se',
                'nama_negara' => 'Swedia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Swedia',
                'nama_kedutaan_besar_en' => 'Embassy of Sweden',
                'format_undangan' => 'Ambassador of Sweden to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Daniel Blockert',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 9)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227161,
                'longitude' => 106.826426,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ch',
                'nama_negara' => 'Swiss',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Swiss',
                'nama_kedutaan_besar_en' => 'Embassy of Switzerland',
                'format_undangan' => 'Ambassador of Switzerland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Olivier Marc Zehnder',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Blok X-3/2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.235045,
                'longitude' => 106.827872,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tz',
                'nama_negara' => 'Tanzania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Persatuan Tanzania',
                'nama_kedutaan_besar_en' => 'Embassy of the United Republic of Tanzania',
                'format_undangan' => 'Ambassador of the United Republic of Tanzania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Macocha Moshe Tembele',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Iskandarsyah II No. 89A',
                'kelurahan' => 'Melawai',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12160',
                'website' => null,
                'latitude' => -6.246916,
                'longitude' => 106.805048,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'th',
                'nama_negara' => 'Thailand',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Thailand',
                'nama_kedutaan_besar_en' => 'Royal Thai Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Thailand to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Prapan Disyatat',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung Kav. E3 Lot 8.8',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.231575,
                'longitude' => 106.828456,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tl',
                'nama_negara' => 'Timor Leste',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Timor Leste',
                'nama_kedutaan_besar_en' => 'Embassy of the Democratic Republic of Timor Leste',
                'format_undangan' => 'Ambassador of the Democratic Republic of Timor Leste to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Roberto Sarmento de Oliveira Soares',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 28 (Mayapada Tower Lt. 19)',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.213808,
                'longitude' => 106.820083,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tn',
                'nama_negara' => 'Tunisia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Tunisia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Tunisia',
                'format_undangan' => 'Ambassador of the Republic of Tunisia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mohamed Trabelsi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Tengah Blok C-5 No. 21, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.226481,
                'longitude' => 106.829227,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tr',
                'nama_negara' => 'Turki',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Turki',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Türkiye',
                'format_undangan' => 'Ambassador of the Republic of Türkiye to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Prof. Dr. Talip Küçükcan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.235879,
                'longitude' => 106.828102,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ua',
                'nama_negara' => 'Ukraina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Ukraina',
                'nama_kedutaan_besar_en' => 'Embassy of Ukraine',
                'format_undangan' => 'Ambassador of Ukraine to the Republic of Indonesia',
                'nama_diplomat' => 'Ms. Yevhenia Shynkarenko',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said (Generali Tower Gran Rubina Business Park Lt. 16, Rasuna Epicentrum)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.219503,
                'longitude' => 106.833323,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
