<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart1Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'af',
                'nama_negara' => 'Afghanistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afghanistan',
                'nama_kedutaan_besar_en' => 'Embassy of Afghanistan',
                'format_undangan' => 'Ambassador of Afghanistan to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Mawlawi Sadullah Baloch',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Dr. Kusuma Atmaja No. 15',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.201290,
                'longitude' => 106.829666,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'za',
                'nama_negara' => 'Afrika Selatan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afrika Selatan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of South Africa',
                'format_undangan' => 'Ambassador of the Republic of South Africa to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mpetjane Kgaogelo Lekgoro',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman No. 28 (Wisma GKBI Lt. 7 Suite 705)',
                'kelurahan' => 'Bendungan Hilir',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10210',
                'website' => null,
                'latitude' => -6.217418,
                'longitude' => 106.812963,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'al',
                'nama_negara' => 'Albania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Albania',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Albania',
                'format_undangan' => 'Ambassador of the Republic of Albania to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Nikson Ballço',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 5-6 (Menara Astra Lt. 38)',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.207247,
                'longitude' => 106.821055,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'dz',
                'nama_negara' => 'Aljazair',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Aljazair',
                'nama_kedutaan_besar_en' => 'Embassy of the People’s Democratic Republic of Algeria',
                'format_undangan' => 'Ambassador of the People’s Democratic Republic of Algeria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdelouahab Osmane',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 10-11',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.230035,
                'longitude' => 106.833666,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'us',
                'nama_negara' => 'Amerika Serikat',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Amerika Serikat',
                'nama_kedutaan_besar_en' => 'Embassy of the United States of America',
                'format_undangan' => 'Ambassador of the United States of America to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Peter Mark Haymond',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Medan Merdeka Selatan No. 3-5',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10110',
                'website' => null,
                'latitude' => -6.180637,
                'longitude' => 106.830099,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ao',
                'nama_negara' => 'Angola',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Angola',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Angola',
                'format_undangan' => 'Ambassador of the Republic of Angola to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Floréncio Mariano da Conceição e Almeida',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Kemang Dalam IX Blok H No. 8',
                'kelurahan' => 'Bangka',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12730',
                'website' => null,
                'latitude' => -6.267839,
                'longitude' => 106.819440,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sa',
                'nama_negara' => 'Arab Saudi',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Arab Saudi',
                'nama_kedutaan_besar_en' => 'Royal Embassy of Saudi Arabia',
                'format_undangan' => 'Ambassador of the Kingdom of Saudi Arabia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Faisal Abdullah H. Amodi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. B2',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.212023,
                'longitude' => 106.830215,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ar',
                'nama_negara' => 'Argentina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Argentina',
                'nama_kedutaan_besar_en' => 'Embassy of the Argentine Republic',
                'format_undangan' => 'Ambassador of the Argentine Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Gustavo Ricardo Coppa',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M. H. Thamrin No. 3 (Menara Thamrin)',
                'kelurahan' => 'Kebon Sirih',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10340',
                'website' => null,
                'latitude' => -6.185705,
                'longitude' => 106.822812,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'am',
                'nama_negara' => 'Armenia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Armenia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Armenia',
                'format_undangan' => 'Ambassador of the Republic of Armenia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Serob Bejanyan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 40',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.226344,
                'longitude' => 106.830952,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'au',
                'nama_negara' => 'Australia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Australia',
                'nama_kedutaan_besar_en' => 'Embassy of Australia',
                'format_undangan' => 'Ambassador of Australia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Roderick Bruce Brazier',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya No. Kav. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.232527,
                'longitude' => 106.834492,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
