<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart3Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'bn',
                'nama_negara' => 'Brunei Darussalam',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Brunei Darussalam',
                'nama_kedutaan_besar_en' => 'Embassy of Brunei Darussalam',
                'format_undangan' => 'Ambassador of Brunei Darussalam to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dato Seri Pahlawan Haji Abdul Razak bin Haji Abd. Kadir',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung (Menara Sun Life)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.230092,
                'longitude' => 106.825673,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bg',
                'nama_negara' => 'Bulgaria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Bulgaria',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Bulgaria',
                'format_undangan' => 'Ambassador of the Republic of Bulgaria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Tanya Dimitrova',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Imam Bonjol No. 34-36',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.199134,
                'longitude' => 106.827725,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cz',
                'nama_negara' => 'Ceko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Ceko',
                'nama_kedutaan_besar_en' => 'Embassy of the Czech Republic',
                'format_undangan' => 'Ambassador of the Czech Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Petr Kopřiva',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Gereja Theresia No. 20',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.191192,
                'longitude' => 106.827754,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cl',
                'nama_negara' => 'Chili',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Chili',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Chile',
                'format_undangan' => 'Ambassador of the Republic of Chile to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mario Ignacio Artaza',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M. H. Thamrin No. 81 (The City Tower Lt. 27)',
                'kelurahan' => 'Dukuh Atas',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.199101,
                'longitude' => 106.823603,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'dk',
                'nama_negara' => 'Denmark',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Denmark',
                'nama_kedutaan_besar_en' => 'Royal Danish Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Denmark to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sten Frimodt Nielsen',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 25)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.226970,
                'longitude' => 106.826418,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ec',
                'nama_negara' => 'Ekuador',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Ekuador',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Ecuador',
                'format_undangan' => 'Ambassador of the Republic of Ecuador to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Luis Guillermo Arellano Jibaja',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 29-31 (World Trade Center 1 Lt. 16)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.214868,
                'longitude' => 106.819953,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'et',
                'nama_negara' => 'Ethiopia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Federal Ethiopia',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Democratic Republic of Ethiopia',
                'format_undangan' => 'Ambassador of the Federal Democratic Republic of Ethiopia to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Fekadu Beyene Aleka',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan IX No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.234260,
                'longitude' => 106.836103,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'fj',
                'nama_negara' => 'Fiji',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kepulauan Fiji',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Fiji',
                'format_undangan' => 'Ambassador of the Republic of Fiji to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Amenatave Vakasavuwaqa Yauvoli',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung (Menara Sun Life Lt. 15)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.230092,
                'longitude' => 106.825673,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ph',
                'nama_negara' => 'Filipina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Filipina',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of the Philippines',
                'format_undangan' => 'Ambassador of the Republic of the Philippines to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Christopher Baltazar Montero',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Imam Bonjol No. 6-8',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.199659,
                'longitude' => 106.830454,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'fi',
                'nama_negara' => 'Finlandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Finlandia',
                'nama_kedutaan_besar_en' => 'Embassy of Finland',
                'format_undangan' => 'Ambassador of Finland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Jukka-Pekka Kaihilahti',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Timur I No. E.1,2 (Menara Rajawali Lt. 9)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227194,
                'longitude' => 106.826411,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
