<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart8Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'fr',
                'nama_negara' => 'Perancis',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Perancis',
                'nama_kedutaan_besar_en' => 'Embassy of France',
                'format_undangan' => 'Ambassador of France to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Fabien Laurent Robert Penone',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'ambassadeur.jakarta-amba@diplomatie.gouv.fr, reception.jakarta-amba@diplomatie.gouv.fr, contact@ambafrance-id.org',
                'telepon_kantor' => '021-2355-7600',
                'alamat' => 'Jl. M.H. Thamrin No. 20',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => 'https://id.ambafrance.org/',
                'latitude' => -6.188599,
                'longitude' => 106.823366,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ae',
                'nama_negara' => 'Persatuan Emirat Arab',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Persatuan Emirat Arab',
                'nama_kedutaan_besar_en' => 'Embassy of the United Arab Emirates',
                'format_undangan' => 'Ambassador of the United Arab Emirates to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdulla Salem Obaid Salem Aldhaheri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mofa.gov.ae, jakartaemb@mofa.gov.ae',
                'telepon_kantor' => '021-520-6518, 021-520-6528, 021-520-6538, 021-520-6552',
                'alamat' => 'Jl. Prof. Dr. Satrio No. C-8, Kuningan',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => 'https://www.mofa.gov.ae/id-id/Missions/Jakarta',
                'latitude' => -6.225800,
                'longitude' => 106.830565,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pe',
                'nama_negara' => 'Peru',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Peru',
                'nama_kedutaan_besar_en' => 'Embassy of Peru',
                'format_undangan' => 'Ambassador of Peru to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Luis Raúl Tsuboyama Galván',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'embaperujak@gmail.com, conperjakarta@gmail.com, khairina.embaperujak@gmail.com, embassy@embaperujak.org, consular@embaperujak.org',
                'telepon_kantor' => '021-576-1820, 021-576-1821',
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung (Menara Rajawali)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://www.gob.pe/embajada-del-peru-en-indonesia',
                'latitude' => -6.227140,
                'longitude' => 106.826428,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pl',
                'nama_negara' => 'Polandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Polandia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Poland',
                'format_undangan' => 'Ambassador of the Republic of Poland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Barbara Magda Szymanowska',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'dzakarta.amb.sekretariat@msz.gov.pl, adinda.sumono@msz.gov.pl',
                'telepon_kantor' => '021-252-5938, 021-252-5939, 021-252-5940',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-1 No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://www.gov.pl/web/indonesia-en/embassy',
                'latitude' => -6.233804,
                'longitude' => 106.830452,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pt',
                'nama_negara' => 'Portugal',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Portugal',
                'nama_kedutaan_besar_en' => 'Embassy of Portugal',
                'format_undangan' => 'Ambassador of Portugal to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Ms. Maria Gabriela Vieira Soares de Albergaria',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'sconsular.jakarta@mne.pt, jakarta@mne.pt, porembjak@cbn.net.id, portindo@cbn.net.id, portrade@cbn.net.id',
                'telepon_kantor' => '021-3190-8030',
                'alamat' => 'Jl. Indramayu No. 2A',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://jacarta.embaixadaportugal.mne.gov.pt/en/',
                'latitude' => -6.195933,
                'longitude' => 106.828413,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'qa',
                'nama_negara' => 'Qatar',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Qatar',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Qatar',
                'format_undangan' => 'Ambassador of the State of Qatar to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Sultan bin Mubarak Saad Al-Dosari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mofa.gov.qa, qataremj@indosat.net.id',
                'telepon_kantor' => '021-5790-6560, 021-5790-6561',
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung No. 5',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://jakarta.embassy.qa/en',
                'latitude' => -6.234119,
                'longitude' => 106.827449,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cn',
                'nama_negara' => 'Republik Rakyat Tiongkok',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rakyat Tiongkok',
                'nama_kedutaan_besar_en' => "Embassy of the People's Republic of China",
                'format_undangan' => "Ambassador of the People's Republic of China to the Republic of Indonesia",
                'nama_diplomat' => 'H.E. Mr. Wang Lutong',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'chinaemb_id@mfa.gov.cn',
                'telepon_kantor' => '021-576-1039, 021-576-1017, 021-576-1037, 021-576-1021, 021-576-1049, 021-576-1036, 021-576-1032, 021-576-1030',
                'alamat' => 'Jl. Mega Kuningan No. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'http://id.china-embassy.gov.cn/eng/',
                'latitude' => -6.225224,
                'longitude' => 106.825660,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ro',
                'nama_negara' => 'Rumania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Rumania',
                'nama_kedutaan_besar_en' => 'Embassy of Romania',
                'format_undangan' => 'Ambassador of Romania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Dan Adrian Bălănescu',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mae.ro, romania.assistant@gmail.com',
                'telepon_kantor' => '021-390-0489, 021-310-6240',
                'alamat' => 'Jl. Teuku Cik Ditiro No. 42A',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'http://jakarta.mae.ro/',
                'latitude' => -6.198068,
                'longitude' => 106.836878,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ru',
                'nama_negara' => 'Rusia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Federasi Rusia',
                'nama_kedutaan_besar_en' => 'Embassy of the Russian Federation',
                'format_undangan' => 'Ambassador of the Russian Federation to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sergei Gennadievich Tolchenov',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'rusemb.indonesia@mid.ru, asean@mid.ru',
                'telepon_kantor' => '021-522-2912, 021-522-2914',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-7 No. 1-2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://indonesia.mid.ru/id/',
                'latitude' => -6.220479,
                'longitude' => 106.831698,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'rw',
                'nama_negara' => 'Rwanda',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rwanda',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Rwanda',
                'format_undangan' => 'Ambassador of the Republic of Rwanda to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sheikh Abdul Karim Harelimana',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'embassy.jakarta@mfa.gov.rw',
                'telepon_kantor' => '021-2359-9277',
                'alamat' => 'Jl. Cianjur No. 15',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.202089,
                'longitude' => 106.828996,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
