<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart2Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'at',
                'nama_negara' => 'Austria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Austria',
                'nama_kedutaan_besar_en' => 'Embassy of Austria',
                'format_undangan' => 'Ambassador of Austria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Thomas Loidi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta-ob@bmeia.gv.at',
                'telepon_kantor' => '021-2355-4005',
                'alamat' => 'Jl. Pangeran Diponegoro No. 44',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://www.bmeia.gv.at/oeb-jakarta/',
                'latitude' => -6.201542,
                'longitude' => 106.839881,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'az',
                'nama_negara' => 'Azerbaijan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Azerbaijan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Azerbaijan',
                'format_undangan' => 'Ambassador of the Republic of Azerbaijan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ramil Rzayev',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mission.mfa.gov.az, azemb.jak@gmail.com',
                'telepon_kantor' => '021-2555-4408',
                'alamat' => 'Jl. Karang Asem Tengah Blok C-5 No. 20',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://jakarta.mfa.gov.az/en',
                'latitude' => -6.226398,
                'longitude' => 106.829553,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bh',
                'nama_negara' => 'Bahrain',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Bahrain',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Bahrain',
                'format_undangan' => 'Ambassador of the Kingdom of Bahrain to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ahmed Abdulla Alharmasi Alhajeri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta.mission@mofa.gov.bh, ymirianti.id@mofa.gov.bh',
                'telepon_kantor' => '021-2902-1810, 021-2902-1811',
                'alamat' => 'Jl. Banyumas No. 2',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.202682,
                'longitude' => 106.832591,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bd',
                'nama_negara' => 'Bangladesh',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Bangladesh',
                'nama_kedutaan_besar_en' => 'Embassy of the People\'s Republic of Bangladesh',
                'format_undangan' => 'Ambassador of the People\'s Republic of Bangladesh to the Republic of Indonesia',
                'nama_diplomat' => 'Ms. Maushumi Rahman',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'mission.jakarta@mofa.gov.bd',
                'telepon_kantor' => '021-2359-9482, 021-2359-9483',
                'alamat' => 'Jl. Denpasar Raya No. 3 Blok A-13 Kav. 10',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://jakarta.mofa.gov.bd/',
                'latitude' => -6.225598,
                'longitude' => 106.828493,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'nl',
                'nama_negara' => 'Belanda',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Belanda',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of the Netherlands',
                'format_undangan' => 'Ambassador of the Kingdom of the Netherlands to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Marc David Gerritsen',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jak@minbuza.nl, jak-cdp@minbuza.nl',
                'telepon_kantor' => '021-524-8200, 021-525-1515',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. S-3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://netherlandsandyou.nl/web/indonesia',
                'latitude' => -6.234573,
                'longitude' => 106.828448,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'by',
                'nama_negara' => 'Belarus',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Belarus',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Belarus',
                'format_undangan' => 'Ambassador of the Republic of Belarus to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Raman Ramanouski',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'indonesia@mfa.gov.by, embassybelarusia@yahoo.co.id, id.consul@mfa.gov.by',
                'telepon_kantor' => '021-525-1388, 021-525-6256',
                'alamat' => 'Jl. Patra Kuningan VII No. 3',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => 'https://indonesia.mfa.gov.by/en/',
                'latitude' => -6.235151,
                'longitude' => 106.834007,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'be',
                'nama_negara' => 'Belgia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Belgia',
                'nama_kedutaan_besar_en' => 'Embassy of Belgium',
                'format_undangan' => 'Ambassador of Belgium to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Frank Leon L. Felix',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@diplobel.fed.be',
                'telepon_kantor' => '021-316-2030',
                'alamat' => 'Jl. Imam Bonjol No. 80 (Deutsche Bank Building Lt. 16)',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => 'https://indonesia.diplomatie.belgium.be/',
                'latitude' => -6.195493,
                'longitude' => 106.824186,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ba',
                'nama_negara' => 'Bosnia dan Herzegovina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Bosnia dan Herzegovina',
                'nama_kedutaan_besar_en' => 'Embassy of Bosnia and Herzegovina',
                'format_undangan' => 'Ambassador of Bosnia and Herzegovina to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Armin Limo',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'amb.dzakarta@mvp.gov.ba, emb.bosnia.herzegovina@gmail.com',
                'telepon_kantor' => '021-8370-3022, 021-8370-3093',
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 1 (Menara Imperium Lt. 11)',
                'kelurahan' => 'Guntur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12980',
                'website' => null,
                'latitude' => -6.210259,
                'longitude' => 106.831571,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'br',
                'nama_negara' => 'Brazil',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federasi Brasil',
                'nama_kedutaan_besar_en' => 'Embassy of the Federative Republic of Brazil',
                'format_undangan' => 'Ambassador of the Federative Republic of Brazil to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. George Monteiro Prata',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'brasemb.jacarta@itamaraty.gov.br, embrasil@cbn.net.id',
                'telepon_kantor' => '021-526-5656, 021-526-5657, 021-526-5658',
                'alamat' => 'Jl. Jend. Gatot Subroto No. 40 (Wisma Mulia 2 Lt. 27)',
                'kelurahan' => 'Kuningan Barat',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12710',
                'website' => 'https://www.gov.br/mre/pt-br/embaixada-jacarta/',
                'latitude' => -6.234451,
                'longitude' => 106.822183,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gb',
                'nama_negara' => 'Britania Raya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Britania Raya',
                'nama_kedutaan_besar_en' => 'Embassy of the United Kingdom',
                'format_undangan' => 'Ambassador of the United Kingdom to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Dominic James Robert Jermey',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta.mcs@fco.gov.uk, jakarta.smt@fcdo.gov.uk, consulate.jakarta@fco.gov.uk',
                'telepon_kantor' => '021-2356-5200',
                'alamat' => 'Jl. Patra Kuningan Raya Blok L5-6',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://www.gov.uk/world/organisations/british-embassy-jakarta',
                'latitude' => -6.235258,
                'longitude' => 106.833216,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
