<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'af',
                'nama_negara' => 'Afghanistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afghanistan',
                'nama_kedutaan_besar_en' => 'Embassy of Afghanistan',
                'format_undangan' => 'Ambassador of Afghanistan to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Mawlawi Sadullah Baloch',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Dr. Kusuma Atmaja No. 15',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1979,
                'longitude' => 106.8291,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'za',
                'nama_negara' => 'Afrika Selatan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afrika Selatan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of South Africa',
                'format_undangan' => 'Ambassador of the Republic of South Africa to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mpetjane Kgaogelo Lekgoro',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Wisma GKBI Lt. 7 Suite 705, Jl. Jend. Sudirman No. 28',
                'kelurahan' => 'Bendungan Hilir',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10210',
                'website' => null,
                'latitude' => -6.2163,
                'longitude' => 106.8118,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'al',
                'nama_negara' => 'Albania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Albania',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Albania',
                'format_undangan' => 'Ambassador of the Republic of Albania to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Nikson Ballço',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Astra Lt. 38, Jl. Jend. Sudirman Kav. 5-6',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.2088,
                'longitude' => 106.8207,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'dz',
                'nama_negara' => 'Aljazair',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Aljazair',
                'nama_kedutaan_besar_en' => 'Embassy of the People’s Democratic Republic of Algeria',
                'format_undangan' => 'Ambassador of the People’s Democratic Republic of Algeria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdelouahab Osmane',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 10-11',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2188,
                'longitude' => 106.8315,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'us',
                'nama_negara' => 'Amerika Serikat',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Amerika Serikat',
                'nama_kedutaan_besar_en' => 'Embassy of the United States of America',
                'format_undangan' => 'Ambassador of the United States of America to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Peter Mark Haymond',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Medan Merdeka Selatan No. 3-5',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10110',
                'website' => null,
                'latitude' => -6.1812,
                'longitude' => 106.8298,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ao',
                'nama_negara' => 'Angola',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Angola',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Angola',
                'format_undangan' => 'Ambassador of the Republic of Angola to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Floréncio Mariano da Conceição e Almeida',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Kemang Dalam IX Blok H No. 8',
                'kelurahan' => 'Bangka',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12730',
                'website' => null,
                'latitude' => -6.2625,
                'longitude' => 106.8139,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sa',
                'nama_negara' => 'Arab Saudi',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Arab Saudi',
                'nama_kedutaan_besar_en' => 'Royal Embassy of Saudi Arabia',
                'format_undangan' => 'Ambassador of the Kingdom of Saudi Arabia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Faisal Abdullah H. Amodi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. B2',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2117,
                'longitude' => 106.8286,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ar',
                'nama_negara' => 'Argentina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Argentina',
                'nama_kedutaan_besar_en' => 'Embassy of the Argentine Republic',
                'format_undangan' => 'Ambassador of the Argentine Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Gustavo Ricardo Coppa',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Thamrin, Jl. M. H. Thamrin No. 3',
                'kelurahan' => 'Kebon Sirih',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10340',
                'website' => null,
                'latitude' => -6.1837,
                'longitude' => 106.8236,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'am',
                'nama_negara' => 'Armenia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Armenia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Armenia',
                'format_undangan' => 'Ambassador of the Republic of Armenia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Serob Bejanyan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 40',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2281,
                'longitude' => 106.8299,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'au',
                'nama_negara' => 'Australia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Australia',
                'nama_kedutaan_besar_en' => 'Embassy of Australia',
                'format_undangan' => 'Ambassador of Australia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Roderick Bruce Brazier',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya No. Kav. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2323,
                'longitude' => 106.8327,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
