<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart6Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'cu',
                'nama_negara' => 'Kuba',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kuba',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Cuba',
                'format_undangan' => 'Ambassador of the Republic of Cuba to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Dagmar González Grau',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Sultan Iskandar Muda Kav. VTA (Pondok Indah Office Tower 1 Lt. 5 No. 501)',
                'kelurahan' => 'Pondok Pinang',
                'kecamatan' => 'Kebayoran Lama',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12310',
                'website' => null,
                'latitude' => -6.266700,
                'longitude' => 106.783300,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kw',
                'nama_negara' => 'Kuwait',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kuwait',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Kuwait',
                'format_undangan' => 'Ambassador of the State of Kuwait to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Khalid Jassim E Al Yassin',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat III No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.232245,
                'longitude' => 106.826682,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'la',
                'nama_negara' => 'Laos',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Laos',
                'nama_kedutaan_besar_en' => "Embassy of the Lao People's Democratic Republic",
                'format_undangan' => "Ambassador of the Lao People's Democratic Republic to the Republic of Indonesia",
                'nama_diplomat' => 'H.E. Mr. Khamfeuang Phanthaxay',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan XIV No. 1A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.229919,
                'longitude' => 106.835407,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'lb',
                'nama_negara' => 'Lebanon',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Lebanon',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Lebanon',
                'format_undangan' => 'Ambassador of the Republic of Lebanon to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Salam Al Achkar',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. YBR V No. 82',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.229666,
                'longitude' => 106.831056,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ly',
                'nama_negara' => 'Libya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Libya',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Libya',
                'format_undangan' => 'Ambassador of the State of Libya to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Zakarya MM El Maghrabi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-7 No. 4',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.221500,
                'longitude' => 106.832200,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'my',
                'nama_negara' => 'Malaysia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Malaysia',
                'nama_kedutaan_besar_en' => 'Embassy of Malaysia',
                'format_undangan' => 'Ambassador of Malaysia to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Farzamie Sarkawi',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-6 No. 1-3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.224828,
                'longitude' => 106.832506,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ma',
                'nama_negara' => 'Maroko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Maroko',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Morocco',
                'format_undangan' => 'Ambassador of the Kingdom of Morocco to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Redouane Houssain',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Denpasar Raya No. 1, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.234168,
                'longitude' => 106.827585,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mr',
                'nama_negara' => 'Mauritania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Mauritania',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Mauritania',
                'format_undangan' => 'Ambassador of the Islamic Republic of Mauritania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Weddady Ould Sidi Haiba',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 52-53 (Artha Graha Building Lt. 23)',
                'kelurahan' => 'Senayan',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12190',
                'website' => null,
                'latitude' => -6.224400,
                'longitude' => 106.810998,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mx',
                'nama_negara' => 'Meksiko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Meksiko',
                'nama_kedutaan_besar_en' => 'Embassy of Mexico',
                'format_undangan' => 'Ambassador of Mexico to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Francisco De La Torre Galindo',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 9-11 (Menara Mulia Lt. 23 Suite 2306)',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.230700,
                'longitude' => 106.818200,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'eg',
                'nama_negara' => 'Mesir',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Arab Mesir',
                'nama_kedutaan_besar_en' => 'Embassy of the Arab Republic of Egypt',
                'format_undangan' => 'Ambassador of the Arab Republic of Egypt to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Yasser Hassan Farag Elshemy',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 68',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.197062,
                'longitude' => 106.832415,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
