<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart7Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'mn',
                'nama_negara' => 'Mongolia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Mongolia',
                'nama_kedutaan_besar_en' => 'Embassy of Mongolia',
                'format_undangan' => 'Ambassador of Mongolia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Enkhtaivan Dashnyam Uyangatsetseg Ulzii-ochir',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mfa.gov.mn',
                'telepon_kantor' => '021-2168-4133',
                'alamat' => 'Jl. Jend. Sudirman Kav. 45-46 (Sampoerna Strategic Square South Tower Lt. 21)',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => 'https://www.mongolianconsulate.org/',
                'latitude' => -6.224000,
                'longitude' => 106.809000,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mz',
                'nama_negara' => 'Mozambik',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Mozambik',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Mozambique',
                'format_undangan' => 'Ambassador of the Republic of Mozambique to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. António Rodrigues José',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'consular.jkt@embamoc-indonesia.com, mozambiquesecretary.id@gmail.com, billing.embamoc@gmail.com, mozambiqueconsular@gmail.com',
                'telepon_kantor' => '021-3825-0075',
                'alamat' => 'Jl. Karang Asem Tengah Blok C4 No. 30',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://embamoc-indonesia.com/',
                'latitude' => -6.227517,
                'longitude' => 106.830794,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mm',
                'nama_negara' => 'Myanmar',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Myanmar',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of the Union of Myanmar',
                'format_undangan' => 'Ambassador of the Republic of the Union of Myanmar to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. U Mang Hau Thang',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => 'mejakarta109@gmail.com, myanmar@cbn.net.id',
                'telepon_kantor' => '021-315-8908, 021-315-9095',
                'alamat' => 'Jl. H. Agus Salim No. 109',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.193993,
                'longitude' => 106.825369,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ng',
                'nama_negara' => 'Nigeria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Nigeria',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Nigeria',
                'format_undangan' => 'Ambassador of the Federal Republic of Nigeria to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Eze Nduka Thomas',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => 'nigeria.jakarta@foreignaffairs.gov.ng, nigembjkt@yahoo.co.id, social_secretary@yahoo.com, embnig@centrin.net.id',
                'telepon_kantor' => '021-526-0922, 021-526-0923, 021-5296-4261',
                'alamat' => 'Jl. Taman Patra XIV No. 11-11A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.239123,
                'longitude' => 106.833817,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'no',
                'nama_negara' => 'Norwegia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Norwegia',
                'nama_kedutaan_besar_en' => 'Royal Norwegian Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Norway to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Rut Krüger Giverin',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'emb.jakarta@mfa.no',
                'telepon_kantor' => '021-2965-0000',
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 20)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://www.norway.no/en/indonesia',
                'latitude' => -6.227426,
                'longitude' => 106.826780,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'om',
                'nama_negara' => 'Oman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kesultanan Oman',
                'nama_kedutaan_besar_en' => 'Embassy of the Sultanate of Oman',
                'format_undangan' => 'Ambassador of the Sultanate of Oman to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sheikh Mohamad Ahmed Salim Al-Shanfari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'jakarta@mofa.gov.om, omanreps@yahoo.com, jakarta@fm.gov.om',
                'telepon_kantor' => '021-3190-8653, 021-3190-8654, 021-3190-8655',
                'alamat' => 'Jl. Latuharhari Raya No. 12',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.205107,
                'longitude' => 106.837904,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pk',
                'nama_negara' => 'Pakistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Pakistan',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Pakistan',
                'format_undangan' => 'Ambassador of the Islamic Republic of Pakistan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Zahid Hafeez Chaudhri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'pakembassyjakarta@gmail.com, parepjakarta@mofa.gov.pk',
                'telepon_kantor' => '021-5785-1836, 021-5785-1837',
                'alamat' => 'Jl. Mega Kuningan Barat Blok E.3.9 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => 'https://www.pakembjakarta.com/',
                'latitude' => -6.230847,
                'longitude' => 106.825841,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ps',
                'nama_negara' => 'Palestina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Palestina',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Palestine',
                'format_undangan' => 'Ambassador of the State of Palestine to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdalfatah Ahmed Khalil Alsattari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'palembid@palestineembassyjakarta.com, palembidsec@palestineembassyjakarta.com',
                'telepon_kantor' => '021-314-5444, 021-3192-3521',
                'alamat' => 'Jl. Ki Mangunsarkoro No. 64',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.202266,
                'longitude' => 106.842878,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pa',
                'nama_negara' => 'Panama',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Panama',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Panama',
                'format_undangan' => 'Ambassador of the Republic of Panama to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Alejandro Arturo Silvera Castillo',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => 'embassy@panamaembassy.net, consular@panamaembassy.net, panaemb@net2cyber.web.id, kedutaan@panamaembassy.net, msaturno@mire.gob.pa',
                'telepon_kantor' => '021-570-0218, 021-571-1867',
                'alamat' => 'Jl. Jend. Sudirman Kav. 29-31 (World Trade Center 1 Lt. 13)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => 'https://mire.gob.pa/ministerio/embajada-y-consulado/jakarta/',
                'latitude' => -6.215348,
                'longitude' => 106.820316,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pg',
                'nama_negara' => 'Papua Nugini',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Papua Nugini',
                'nama_kedutaan_besar_en' => 'Embassy of the Independent State of Papua New Guinea',
                'format_undangan' => 'Ambassador of the Independent State of Papua New Guinea to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Simon Namis',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => 'kdujkt@cbn.net.id, pngemb.jakarta@dfa.gov.pg, inquiries.jakatar@dfa.gov.pg',
                'telepon_kantor' => '021-725-1218, 021-725-1225, 021-725-1742',
                'alamat' => 'Jl. Jend. Sudirman No. 1 (Panin Bank Centre Lt. 6)',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => 'https://www.kundu-jakarta.com/',
                'latitude' => -6.228058,
                'longitude' => 106.799555,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
