<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart9Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'sm',
                'nama_negara' => 'San Marino',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik San Marino',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of San Marino',
                'format_undangan' => 'Ambassador of the Republic of San Marino to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Massimo Ferdinandi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 15)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227126,
                'longitude' => 106.826364,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'nz',
                'nama_negara' => 'Selandia Baru',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Selandia Baru',
                'nama_kedutaan_besar_en' => 'New Zealand Embassy',
                'format_undangan' => 'Ambassador of New Zealand to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Phillip Taula',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Asia Afrika No. 8 (Sentral Senayan II Lt. 10)',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => null,
                'latitude' => -6.223697,
                'longitude' => 106.798916,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'rs',
                'nama_negara' => 'Serbia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Serbia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Serbia',
                'format_undangan' => 'Ambassador of the Republic of Serbia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Ivana Golubović - Duboka',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.O.S. Cokroaminoto No. 109',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.201214,
                'longitude' => 106.828256,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sg',
                'nama_negara' => 'Singapura',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Singapura',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Singapore',
                'format_undangan' => 'Ambassador of the Republic of Singapore to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Kwok Fook Seng',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Blok X/4 Kav. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.233922,
                'longitude' => 106.829830,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cy',
                'nama_negara' => 'Siprus',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Siprus',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Cyprus',
                'format_undangan' => 'Ambassador of the Republic of Cyprus to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Nikos Panayiotou',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 29-31 (World Trade Center 3)',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.214649,
                'longitude' => 106.820673,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sk',
                'nama_negara' => 'Slovakia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Slovakia',
                'nama_kedutaan_besar_en' => 'Embassy of the Slovak Republic',
                'format_undangan' => 'Ambassador of the Slovak Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Thomas Ferko',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Prof. Mohammad Yamin No. 29',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.196151,
                'longitude' => 106.832159,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'so',
                'nama_negara' => 'Somalia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Somalia',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Somalia',
                'format_undangan' => 'Ambassador of the Federal Republic of Somalia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Faysal Ahmed Salad',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Raya Casablanca Kav. 88 (EightyEight@Kasablanka Office Tower Lt. 27)',
                'kelurahan' => 'Menteng Dalam',
                'kecamatan' => 'Tebet',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12870',
                'website' => null,
                'latitude' => -6.224328,
                'longitude' => 106.841942,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'es',
                'nama_negara' => 'Spanyol',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Spanyol',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Spain',
                'format_undangan' => 'Ambassador of the Kingdom of Spain to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Bernardo de Sicard Escoda',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.A.R. Salim No. 61',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.187278,
                'longitude' => 106.825363,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'lk',
                'nama_negara' => 'Sri Lanka',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Sri Lanka',
                'nama_kedutaan_besar_en' => 'Embassy of the Democratic Socialist Republic of Sri Lanka',
                'format_undangan' => 'Ambassador of the Democratic Socialist Republic of Sri Lanka to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Sumadhurika Sashikala Premawardhane',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pangeran Diponegoro No. 70',
                'kelurahan' => 'Pegangsaan',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10320',
                'website' => null,
                'latitude' => -6.200131,
                'longitude' => 106.844987,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sd',
                'nama_negara' => 'Sudan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Sudan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Sudan',
                'format_undangan' => 'Ambassador of the Republic of Sudan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Yassir Mohamed Ali',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan 14 No. 7',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.229966,
                'longitude' => 106.836278,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
