<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart2Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'bn',
                'nama_negara' => 'Brunei Darussalam',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Brunei Darussalam',
                'nama_kedutaan_besar_en' => 'Embassy of Brunei Darussalam',
                'format_undangan' => 'Ambassador of Brunei Darussalam to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dato Seri Pahlawan Haji Abdul Razak bin Haji Abd. Kadir',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Sun Life, Jl. DR. Ide Anak Agung Gde Agung',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2294,
                'longitude' => 106.8288,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bg',
                'nama_negara' => 'Bulgaria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Bulgaria',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Bulgaria',
                'format_undangan' => 'Ambassador of the Republic of Bulgaria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Tanya Dimitrova',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Imam Bonjol No. 34-36',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1982,
                'longitude' => 106.8285,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cz',
                'nama_negara' => 'Ceko',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Ceko',
                'nama_kedutaan_besar_en' => 'Embassy of the Czech Republic',
                'format_undangan' => 'Ambassador of the Czech Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Petr Kopřiva',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Gereja Theresia No. 20',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1895,
                'longitude' => 106.8251,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cl',
                'nama_negara' => 'Chili',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Chili',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Chile',
                'format_undangan' => 'Ambassador of the Republic of Chile to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mario Ignacio Artaza',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Gedung Bina Mulia II Lt. 7, Jl. H. R. Rasuna Said Kav. X-5 No. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2251,
                'longitude' => 106.8322,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'dk',
                'nama_negara' => 'Denmark',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Denmark',
                'nama_kedutaan_besar_en' => 'Royal Danish Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Denmark to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sten Frimodt Nielsen',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 25, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ec',
                'nama_negara' => 'Ekuador',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Ekuador',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Ecuador',
                'format_undangan' => 'Ambassador of the Republic of Ecuador to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Luis Guillermo Arellano Jibaja',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Center 5 Lt. 3, Jl. Jend. Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2161,
                'longitude' => 106.8185,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'et',
                'nama_negara' => 'Ethiopia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Federal Ethiopia',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Democratic Republic of Ethiopia',
                'format_undangan' => 'Ambassador of the Federal Democratic Republic of Ethiopia to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Fekadu Beyene Aleka',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan XI No. 8',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2382,
                'longitude' => 106.8361,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'fj',
                'nama_negara' => 'Fiji',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kepulauan Fiji',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Fiji',
                'format_undangan' => 'Ambassador of the Republic of Fiji to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Amenatave Vakasavuwaqa Yauvoli',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Sun Life Lt. 15, Jl. DR. Ide Anak Agung Gde Agung',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2294,
                'longitude' => 106.8288,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ph',
                'nama_negara' => 'Filipina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Filipina',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of the Philippines',
                'format_undangan' => 'Ambassador of the Republic of the Philippines to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Christopher Baltazar Montero',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Imam Bonjol No. 6-8',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1983,
                'longitude' => 106.8268,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'fi',
                'nama_negara' => 'Finlandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Finlandia',
                'nama_kedutaan_besar_en' => 'Embassy of Finland',
                'format_undangan' => 'Ambassador of Finland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Jukka-Pekka Kaihilahti',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 9, Jl. Mega Kuningan Timur I No. E.1,2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8251,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ge',
                'nama_negara' => 'Georgia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Georgia',
                'nama_kedutaan_besar_en' => 'Embassy of Georgia',
                'format_undangan' => 'Ambassador of Georgia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Tornike Nozadze',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Denpasar Barat Blok C6 No. 19A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2255,
                'longitude' => 106.8302,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gt',
                'nama_negara' => 'Guatemala',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Guatemala',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Guatemala',
                'format_undangan' => 'Ambassador of the Republic of Guatemala to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Manuel Estuardo Roldán Barillas',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 11, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'hu',
                'nama_negara' => 'Hungaria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Hungaria',
                'nama_kedutaan_besar_en' => 'Embassy of Hungary',
                'format_undangan' => 'Ambassador of Hungary to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Ms. Lilla Karsay',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-3 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2347,
                'longitude' => 106.8329,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'in',
                'nama_negara' => 'India',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar India',
                'nama_kedutaan_besar_en' => 'Embassy of India',
                'format_undangan' => 'Ambassador of India to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sandeep Chakravorty',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Gama Tower, Jl. H. R. Rasuna Said Kav. C22',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2239,
                'longitude' => 106.8361,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'iq',
                'nama_negara' => 'Irak',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Irak',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Iraq',
                'format_undangan' => 'Ambassador of the Republic of Iraq to the Republic of Indonesia',
                'nama_diplomat' => 'Dr. Ammar Hameed Saadallah Al-Khalidy',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 8',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1882,
                'longitude' => 106.8322,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ir',
                'nama_negara' => 'Iran',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Iran',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Iran',
                'format_undangan' => 'Ambassador of the Islamic Republic of Iran to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mohammad Boroujerdi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.O.S. Cokroaminoto No. 110',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.2005,
                'longitude' => 106.8318,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ie',
                'nama_negara' => 'Irlandia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Irlandia',
                'nama_kedutaan_besar_en' => 'Embassy of Ireland',
                'format_undangan' => 'Ambassador of Ireland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Sharon Ann Lennon',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Center 1 Lt. 14, Jl. Jenderal Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.2157,
                'longitude' => 106.8188,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'it',
                'nama_negara' => 'Italia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Italia',
                'nama_kedutaan_besar_en' => 'Embassy of Italy',
                'format_undangan' => 'Ambassador of Italy to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Roberto Colaminè',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pangeran Diponegoro No. 45',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1989,
                'longitude' => 106.8389,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'jp',
                'nama_negara' => 'Jepang',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Jepang',
                'nama_kedutaan_besar_en' => 'Embassy of Japan',
                'format_undangan' => 'Ambassador of Japan to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Myochin Mitsuru',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M.H. Thamrin No. 24',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1932,
                'longitude' => 106.8242,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'de',
                'nama_negara' => 'Jerman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Jerman',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Germany',
                'format_undangan' => 'Ambassador of the Federal Republic of Germany to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ralf Beste',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M.H. Thamrin No. 1',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1953,
                'longitude' => 106.8231,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
