<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart11Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'eu',
                'nama_negara' => 'Uni Eropa',
                'nama_kedutaan_besar_id' => 'Delegasi Uni Eropa',
                'nama_kedutaan_besar_en' => 'Delegation of the European Union',
                'format_undangan' => 'Ambassador of the European Union to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Denis Chaibi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 5-6 (Menara Astra Lt. 38)',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.207114,
                'longitude' => 106.821451,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'uy',
                'nama_negara' => 'Uruguay',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Uruguay',
                'nama_kedutaan_besar_en' => 'Embassy of the Oriental Republic of Uruguay',
                'format_undangan' => 'Ambassador of the Oriental Republic of Uruguay to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Cristina Gonzalez',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung (Menara Rajawali Lt. 12)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227975,
                'longitude' => 106.825239,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'uz',
                'nama_negara' => 'Uzbekistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Uzbekistan',
                'nama_kedutaan_besar_en' => 'Embassy of Uzbekistan',
                'format_undangan' => 'Ambassador of Uzbekistan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Oybek Eshonov',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Aditiyawarman No. 25',
                'kelurahan' => 'Selong',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12110',
                'website' => null,
                'latitude' => -6.236602,
                'longitude' => 106.804515,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'va',
                'nama_negara' => 'Vatikan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Tahta Suci Vatikan',
                'nama_kedutaan_besar_en' => 'Apostolic Nunciature',
                'format_undangan' => 'Apostolic Nuncio to the Republic of Indonesia',
                'nama_diplomat' => 'Fr. Michael Andrew Pawlowicz',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Medan Merdeka Timur No. 18',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10110',
                'website' => null,
                'latitude' => -6.180004,
                'longitude' => 106.832328,
                'is_active' => true,
            ],
            [
                'kode_negara' => 've',
                'nama_negara' => 'Venezuela',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Venezuela',
                'nama_kedutaan_besar_en' => 'Embassy of the Bolivarian Republic of Venezuela',
                'format_undangan' => 'Ambassador of the Bolivarian Republic of Venezuela to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Enrique Antonio Acuña Mendoza',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. C 11-14 (Plaza Kuningan Menara Utara Lt. 3 Suite 302)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.216814,
                'longitude' => 106.831389,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'vn',
                'nama_negara' => 'Vietnam',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Vietnam',
                'nama_kedutaan_besar_en' => 'Embassy of the Socialist Republic of Vietnam',
                'format_undangan' => 'Ambassador of the Socialist Republic of Vietnam to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ta Van Thông',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 25',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.193227,
                'longitude' => 106.833409,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ye',
                'nama_negara' => 'Yaman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Yaman',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Yemen',
                'format_undangan' => 'Ambassador of the Republic of Yemen to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Salem Ahmad Abdullah Balfakeeh',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Latuharhary No. 16',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.203382,
                'longitude' => 106.829027,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'jo',
                'nama_negara' => 'Yordania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Hasyimiyah Yordania',
                'nama_kedutaan_besar_en' => 'Embassy of the Hashemite Kingdom of Jordan',
                'format_undangan' => 'Ambassador of the Hashemite Kingdom of Jordan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sudqi Atallah Abdel Qader al Omoush',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 52-53 (Artha Graha Tower Lt. 9)',
                'kelurahan' => 'Senayan',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12190',
                'website' => null,
                'latitude' => -6.224510,
                'longitude' => 106.811109,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gr',
                'nama_negara' => 'Yunani',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Yunani',
                'nama_kedutaan_besar_en' => 'Embassy of the Hellenic Republic',
                'format_undangan' => 'Ambassador of the Hellenic Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Dimitrios Michalopoulos',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. X-7 No. 6 (Plaza 89 Lt. 12)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.217699,
                'longitude' => 106.830573,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'zw',
                'nama_negara' => 'Zimbabwe',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Zimbabwe',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Zimbabwe',
                'format_undangan' => 'Ambassador of the Republic of Zimbabwe to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Martin Makururu',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan VII No. 15',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.235364,
                'longitude' => 106.836080,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
