<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart5Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'kh',
                'nama_negara' => 'Kamboja',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kamboja',
                'nama_kedutaan_besar_en' => 'Royal Embassy of Cambodia',
                'format_undangan' => 'Ambassador of the Kingdom of Cambodia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Tean Samnang',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. TB. Simatupang Kav. 13',
                'kelurahan' => 'Ragunan',
                'kecamatan' => 'Pasar Minggu',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12540',
                'website' => null,
                'latitude' => -6.277696,
                'longitude' => 106.826078,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ca',
                'nama_negara' => 'Kanada',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kanada',
                'nama_kedutaan_besar_en' => 'Embassy of Canada',
                'format_undangan' => 'Ambassador of Canada to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Jess Dutton',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 29-31 (World Trade Center 1 Lt. 6)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.215103,
                'longitude' => 106.820207,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kz',
                'nama_negara' => 'Kazakhstan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kazakhstan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Kazakhstan',
                'format_undangan' => 'Ambassador of the Republic of Kazakhstan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Serzhan Abdykarimov',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya Blok M7 Kav. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.235798,
                'longitude' => 106.833290,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ke',
                'nama_negara' => 'Kenya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kenya',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Kenya',
                'format_undangan' => 'Ambassador of the Republic of Kenya to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdirashid Salat Abdille',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karawang No. 4',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.199000,
                'longitude' => 106.833000,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sb',
                'nama_negara' => 'Kepulauan Solomon',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kepulauan Solomon',
                'nama_kedutaan_besar_en' => 'Embassy of the Solomon Islands',
                'format_undangan' => 'Ambassador of the Solomon Islands to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Gladys Kamia Isihanua',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 33A (ANZ Tower Lt. 23)',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.208200,
                'longitude' => 106.819600,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'co',
                'nama_negara' => 'Kolombia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kolombia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Colombia',
                'format_undangan' => 'Ambassador of the Republic of Colombia to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Carlos Alberto Dueñas Morales',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 47 (Sentral Plaza Lt. 12)',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.216816,
                'longitude' => 106.816439,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kr',
                'nama_negara' => 'Korea Selatan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Korea',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Korea',
                'format_undangan' => 'Ambassador of the Republic of Korea to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Yoon Soon-gu',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 57',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.239598,
                'longitude' => 106.832620,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kp',
                'nama_negara' => 'Korea Utara',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Rakyat Demokratik Korea',
                'nama_kedutaan_besar_en' => "Embassy of the Democratic People's Republic of Korea",
                'format_undangan' => "Ambassador of the Democratic People's Republic of Korea to the Republic of Indonesia",
                'nama_diplomat' => 'Mr. So Kwang Yun',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Sumenep',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.203044,
                'longitude' => 106.827411,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cr',
                'nama_negara' => 'Kosta Rika',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kosta Rika',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Costa Rica',
                'format_undangan' => 'Ambassador of the Republic of Costa Rica to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Francisco José Masís Holdridge',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 12)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227126,
                'longitude' => 106.826364,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'hr',
                'nama_negara' => 'Kroasia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Kroasia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Croatia',
                'format_undangan' => 'Ambassador of the Republic of Croatia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Nebojša Koharović',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 9-11 (Menara Mulia Lt. 28 Suite 2801)',
                'kelurahan' => 'Kuningan Barat',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12710',
                'website' => null,
                'latitude' => -6.224226,
                'longitude' => 106.816571,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
