<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart7Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'mn',
                'nama_negara' => 'Mongolia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Mongolia',
                'nama_kedutaan_besar_en' => 'Embassy of Mongolia',
                'format_undangan' => 'Ambassador of Mongolia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Enkhtaivan Dashnyam Uyangatsetseg Ulzii-ochir',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 45-46 (Sampoerna Strategic Square South Tower Lt. 21)',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.224000,
                'longitude' => 106.809000,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mz',
                'nama_negara' => 'Mozambik',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Mozambik',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Mozambique',
                'format_undangan' => 'Ambassador of the Republic of Mozambique to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. António Rodrigues José',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Tengah Blok C4 No. 30',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227517,
                'longitude' => 106.830794,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mm',
                'nama_negara' => 'Myanmar',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Myanmar',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of the Union of Myanmar',
                'format_undangan' => 'Ambassador of the Republic of the Union of Myanmar to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. U Mang Hau Thang',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. Agus Salim No. 109',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.193993,
                'longitude' => 106.825369,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ng',
                'nama_negara' => 'Nigeria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Nigeria',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Nigeria',
                'format_undangan' => 'Ambassador of the Federal Republic of Nigeria to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Eze Nduka Thomas',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Taman Patra XIV No. 11-11A',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.239123,
                'longitude' => 106.833817,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'no',
                'nama_negara' => 'Norwegia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Norwegia',
                'nama_kedutaan_besar_en' => 'Royal Norwegian Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Norway to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Rut Krüger Giverin',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat No. 3 (Menara Rajawali Lt. 20)',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227426,
                'longitude' => 106.826780,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'om',
                'nama_negara' => 'Oman',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kesultanan Oman',
                'nama_kedutaan_besar_en' => 'Embassy of the Sultanate of Oman',
                'format_undangan' => 'Ambassador of the Sultanate of Oman to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Sheikh Mohamad Ahmed Salim Al-Shanfari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Latuharhari Raya No. 12',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.205107,
                'longitude' => 106.837904,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pk',
                'nama_negara' => 'Pakistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Islam Pakistan',
                'nama_kedutaan_besar_en' => 'Embassy of the Islamic Republic of Pakistan',
                'format_undangan' => 'Ambassador of the Islamic Republic of Pakistan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Zahid Hafeez Chaudhri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Mega Kuningan Barat Blok E.3.9 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.230847,
                'longitude' => 106.825841,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ps',
                'nama_negara' => 'Palestina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Palestina',
                'nama_kedutaan_besar_en' => 'Embassy of the State of Palestine',
                'format_undangan' => 'Ambassador of the State of Palestine to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdalfatah Ahmed Khalil Alsattari',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Ki Mangunsarkoro No. 64',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.202266,
                'longitude' => 106.842878,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pa',
                'nama_negara' => 'Panama',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Panama',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Panama',
                'format_undangan' => 'Ambassador of the Republic of Panama to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Alejandro Arturo Silvera Castillo',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman Kav. 29-31 (World Trade Center 1 Lt. 13)',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.215348,
                'longitude' => 106.820316,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'pg',
                'nama_negara' => 'Papua Nugini',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Papua Nugini',
                'nama_kedutaan_besar_en' => 'Embassy of the Independent State of Papua New Guinea',
                'format_undangan' => 'Ambassador of the Independent State of Papua New Guinea to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Simon Namis',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Jend. Sudirman No. 1 (Panin Bank Centre Lt. 6)',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => null,
                'latitude' => -6.228058,
                'longitude' => 106.799555,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
