<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart1Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'af',
                'nama_negara' => 'Afghanistan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afghanistan',
                'nama_kedutaan_besar_en' => 'Embassy of Afghanistan',
                'format_undangan' => 'Ambassador of Afghanistan to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Mawlawi Sadullah Baloch',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Dr. Kusuma Atmaja No. 15',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1979,
                'longitude' => 106.8291,
                'is_active' => true,  // Is_Active kosong di sheet, di-default true — mohon konfirmasi
            ],
            [
                'kode_negara' => 'za',
                'nama_negara' => 'Afrika Selatan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Afrika Selatan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of South Africa',
                'format_undangan' => 'Ambassador of the Republic of South Africa to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mpetjane Kgaogelo Lekgoro',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Wisma GKBI Lt. 7 Suite 705, Jl. Jend. Sudirman No. 28',
                'kelurahan' => 'Bendungan Hilir',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10210',
                'website' => null,
                'latitude' => -6.2163,
                'longitude' => 106.8118,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'al',
                'nama_negara' => 'Albania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Albania',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Albania',
                'format_undangan' => 'Ambassador of the Republic of Albania to the Republic of Indonesia',
                'nama_diplomat' => 'Mr. Nikson Ballço',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Astra Lt. 38, Jl. Jend. Sudirman Kav. 5-6',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.2088,
                'longitude' => 106.8207,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'dz',
                'nama_negara' => 'Aljazair',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Demokratik Aljazair',
                'nama_kedutaan_besar_en' => 'Embassy of the People’s Democratic Republic of Algeria',
                'format_undangan' => 'Ambassador of the People’s Democratic Republic of Algeria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdelouahab Osmane',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 10-11',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2188,
                'longitude' => 106.8315,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'us',
                'nama_negara' => 'Amerika Serikat',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Amerika Serikat',
                'nama_kedutaan_besar_en' => 'Embassy of the United States of America',
                'format_undangan' => 'Ambassador of the United States of America to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Peter Mark Haymond',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Medan Merdeka Selatan No. 3-5',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10110',
                'website' => null,
                'latitude' => -6.1812,
                'longitude' => 106.8298,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ao',
                'nama_negara' => 'Angola',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Angola',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Angola',
                'format_undangan' => 'Ambassador of the Republic of Angola to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Floréncio Mariano da Conceição e Almeida',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Kemang Dalam IX Blok H No. 8',
                'kelurahan' => 'Bangka',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12730',
                'website' => null,
                'latitude' => -6.2625,
                'longitude' => 106.8139,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sa',
                'nama_negara' => 'Arab Saudi',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Arab Saudi',
                'nama_kedutaan_besar_en' => 'Royal Embassy of Saudi Arabia',
                'format_undangan' => 'Ambassador of the Kingdom of Saudi Arabia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Faisal Abdullah H. Amodi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. B2',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2117,
                'longitude' => 106.8286,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ar',
                'nama_negara' => 'Argentina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Argentina',
                'nama_kedutaan_besar_en' => 'Embassy of the Argentine Republic',
                'format_undangan' => 'Ambassador of the Argentine Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Gustavo Ricardo Coppa',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Thamrin, Jl. M. H. Thamrin No. 3',
                'kelurahan' => 'Kebon Sirih',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10340',
                'website' => null,
                'latitude' => -6.1837,
                'longitude' => 106.8236,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'am',
                'nama_negara' => 'Armenia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Armenia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Armenia',
                'format_undangan' => 'Ambassador of the Republic of Armenia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Serob Bejanyan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 40',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2281,
                'longitude' => 106.8299,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'au',
                'nama_negara' => 'Australia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Australia',
                'nama_kedutaan_besar_en' => 'Embassy of Australia',
                'format_undangan' => 'Ambassador of Australia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Roderick Bruce Brazier',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya No. Kav. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2323,
                'longitude' => 106.8327,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'at',
                'nama_negara' => 'Austria',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Austria',
                'nama_kedutaan_besar_en' => 'Embassy of Austria',
                'format_undangan' => 'Ambassador of Austria to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Thomas Loidi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pangeran Diponegoro No. 44',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.199,
                'longitude' => 106.8384,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'az',
                'nama_negara' => 'Azerbaijan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Azerbaijan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Azerbaijan',
                'format_undangan' => 'Ambassador of the Republic of Azerbaijan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ramil Rzayev',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 41',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2282,
                'longitude' => 106.8301,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bh',
                'nama_negara' => 'Bahrain',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Bahrain',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Bahrain',
                'format_undangan' => 'Ambassador of the Kingdom of Bahrain to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Ahmed Abdulla Alharmasi Alhajeri',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung Kav. E.1.1 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2285,
                'longitude' => 106.8274,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'bd',
                'nama_negara' => 'Bangladesh',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Bangladesh',
                'nama_kedutaan_besar_en' => 'Embassy of the People\'s Republic of Bangladesh',
                'format_undangan' => 'Ambassador of the People\'s Republic of Bangladesh to the Republic of Indonesia',
                'nama_diplomat' => 'Ms. Maushumi Rahman',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 12',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2285,
                'longitude' => 106.8305,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'nl',
                'nama_negara' => 'Belanda',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Belanda',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of the Netherlands',
                'format_undangan' => 'Ambassador of the Kingdom of the Netherlands to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Marc David Gerritsen',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. HR Rasuna Said Kav. S-3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2372,
                'longitude' => 106.8329,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'by',
                'nama_negara' => 'Belarus',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Belarus',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Belarus',
                'format_undangan' => 'Ambassador of the Republic of Belarus to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Raman Ramanouski',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan VII No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2361,
                'longitude' => 106.8352,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'be',
                'nama_negara' => 'Belgia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Belgia',
                'nama_kedutaan_besar_en' => 'Embassy of Belgium',
                'format_undangan' => 'Ambassador of Belgium to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Frank Leon L. Felix',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Deutsche Bank Building Lt. 16, Jl. Imam Bonjol No. 80',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1973,
                'longitude' => 106.8234,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ba',
                'nama_negara' => 'Bosnia dan Herzegovina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Bosnia dan Herzegovina',
                'nama_kedutaan_besar_en' => 'Embassy of Bosnia and Herzegovina',
                'format_undangan' => 'Ambassador of Bosnia and Herzegovina to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Armin Limo',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Imperium Lt. 11, Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Guntur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12980',
                'website' => null,
                'latitude' => -6.2104,
                'longitude' => 106.8306,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'br',
                'nama_negara' => 'Brazil',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federasi Brasil',
                'nama_kedutaan_besar_en' => 'Embassy of the Federative Republic of Brazil',
                'format_undangan' => 'Ambassador of the Federative Republic of Brazil to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. George Monteiro Prata',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Mulia Lt. 16, Jl. Jend. Gatot Subroto Kav. 9-11',
                'kelurahan' => 'Karet Semanggi',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12930',
                'website' => null,
                'latitude' => -6.2307,
                'longitude' => 106.8182,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gb',
                'nama_negara' => 'Britania Raya',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Britania Raya',
                'nama_kedutaan_besar_en' => 'Embassy of the United Kingdom',
                'format_undangan' => 'Ambassador of the United Kingdom to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Dominic James Robert Jermey',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya Blok L5-6',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2349,
                'longitude' => 106.8335,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
