<?php

namespace Database\Seeders;

use App\Models\KedutaanBesar;
use Illuminate\Database\Seeder;

class KedutaanBesarPart5Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'sm',
                'nama_negara' => 'San Marino',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik San Marino',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of San Marino',
                'format_undangan' => 'Ambassador of the Republic of San Marino to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Massimo Ferdinandi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 15, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'nz',
                'nama_negara' => 'Selandia Baru',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Selandia Baru',
                'nama_kedutaan_besar_en' => 'New Zealand Embassy',
                'format_undangan' => 'Ambassador of New Zealand to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Phillip Taula',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Sentral Senayan II Lt. 10, Jl. Asia Afrika No. 8',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => null,
                'latitude' => -6.2252,
                'longitude' => 106.8001,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'rs',
                'nama_negara' => 'Serbia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Serbia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Serbia',
                'format_undangan' => 'Ambassador of the Republic of Serbia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Ivana Golubović - Duboka',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.O.S. Cokroaminoto No. 109',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.2001,
                'longitude' => 106.8315,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sg',
                'nama_negara' => 'Singapura',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Singapura',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Singapore',
                'format_undangan' => 'Ambassador of the Republic of Singapore to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Kwok Fook Seng',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Blok X/4 Kav. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2332,
                'longitude' => 106.8328,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cy',
                'nama_negara' => 'Siprus',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Siprus',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Cyprus',
                'format_undangan' => 'Ambassador of the Republic of Cyprus to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Nikos Panayiotou',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 18, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sk',
                'nama_negara' => 'Slovakia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Slovakia',
                'nama_kedutaan_besar_en' => 'Embassy of the Slovak Republic',
                'format_undangan' => 'Ambassador of the Slovak Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E Mr. Thomas Ferko',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Prof. Mohammad Yamin No. 29',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1989,
                'longitude' => 106.8312,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'so',
                'nama_negara' => 'Somalia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Federal Somalia',
                'nama_kedutaan_besar_en' => 'Embassy of the Federal Republic of Somalia',
                'format_undangan' => 'Ambassador of the Federal Republic of Somalia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Faysal Ahmed Salad',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem I No. 2, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.227,
                'longitude' => 106.8305,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'es',
                'nama_negara' => 'Spanyol',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Kerajaan Spanyol',
                'nama_kedutaan_besar_en' => 'Embassy of the Kingdom of Spain',
                'format_undangan' => 'Ambassador of the Kingdom of Spain to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Bernardo de Sicard Escoda',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.A.R. Salim No. 61',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1895,
                'longitude' => 106.8256,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'lk',
                'nama_negara' => 'Sri Lanka',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Sri Lanka',
                'nama_kedutaan_besar_en' => 'Embassy of the Democratic Socialist Republic of Sri Lanka',
                'format_undangan' => 'Ambassador of the Democratic Socialist Republic of Sri Lanka to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mrs. Sumadhurika Sashikala Premawardhane',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pangeran Diponegoro No. 70',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1991,
                'longitude' => 106.8435,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sd',
                'nama_negara' => 'Sudan',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Sudan',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Sudan',
                'format_undangan' => 'Ambassador of the Republic of Sudan to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Dr. Yassir Mohamed Ali',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Teuku Umar No. 60',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1972,
                'longitude' => 106.833,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sy',
                'nama_negara' => 'Suriah',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Arab Suriah',
                'nama_kedutaan_besar_en' => 'Embassy of the Syrian Arab Republic',
                'format_undangan' => 'Ambassador of the Syrian Arab Republic to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Abdulmonem Annan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem I No. 8, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2272,
                'longitude' => 106.8308,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sr',
                'nama_negara' => 'Suriname',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Suriname',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Suriname',
                'format_undangan' => 'Ambassador of the Republic of Suriname to the Republic of Indonesia',
                'nama_diplomat' => 'H. E. Mr. Erick Rahmat Moertabat',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Utara Blok C4 No. 16',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2283,
                'longitude' => 106.8292,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'se',
                'nama_negara' => 'Swedia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Swedia',
                'nama_kedutaan_besar_en' => 'Embassy of Sweden',
                'format_undangan' => 'Ambassador of Sweden to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Daniel Blockert',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Rajawali Lt. 9, Jl. Mega Kuningan Barat No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2263,
                'longitude' => 106.8249,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ch',
                'nama_negara' => 'Swiss',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Swiss',
                'nama_kedutaan_besar_en' => 'Embassy of Switzerland',
                'format_undangan' => 'Ambassador of Switzerland to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Olivier Marc Zehnder',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Blok X-3/2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2348,
                'longitude' => 106.8331,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tz',
                'nama_negara' => 'Tanzania',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Persatuan Tanzania',
                'nama_kedutaan_besar_en' => 'Embassy of the United Republic of Tanzania',
                'format_undangan' => 'Ambassador of the United Republic of Tanzania to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Macocha Moshe Tembele',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem IX No. 6, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2289,
                'longitude' => 106.8321,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'th',
                'nama_negara' => 'Thailand',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Thailand',
                'nama_kedutaan_besar_en' => 'Royal Thai Embassy',
                'format_undangan' => 'Ambassador of the Kingdom of Thailand to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Prapan Disyatat',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. DR. Ide Anak Agung Gde Agung No. 1, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2285,
                'longitude' => 106.8275,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tl',
                'nama_negara' => 'Timor Leste',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Timor Leste',
                'nama_kedutaan_besar_en' => 'Embassy of the Democratic Republic of Timor Leste',
                'format_undangan' => 'Ambassador of the Democratic Republic of Timor Leste to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Roberto Sarmento de Oliveira Soares',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Surya Building Lt. 11, Jl. M.H. Thamrin No. 9',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1872,
                'longitude' => 106.8239,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tn',
                'nama_negara' => 'Tunisia',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Republik Tunisia',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Tunisia',
                'format_undangan' => 'Ambassador of the Republic of Tunisia to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Mr. Mohamed Trabelsi',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Karang Asem Tengah No. 5, Kuningan',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2279,
                'longitude' => 106.8311,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tr',
                'nama_negara' => 'Turki',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Turki',
                'nama_kedutaan_besar_en' => 'Embassy of the Republic of Türkiye',
                'format_undangan' => 'Ambassador of the Republic of Türkiye to the Republic of Indonesia',
                'nama_diplomat' => 'H.E. Prof. Dr. Talip Küçükcan',
                'jabatan_diplomat' => 'Dubes',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H. R. Rasuna Said Kav. 1',
                'kelurahan' => 'Karet Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2238,
                'longitude' => 106.8325,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ua',
                'nama_negara' => 'Ukraina',
                'nama_kedutaan_besar_id' => 'Kedutaan Besar Ukraina',
                'nama_kedutaan_besar_en' => 'Embassy of Ukraine',
                'format_undangan' => 'Ambassador of Ukraine to the Republic of Indonesia',
                'nama_diplomat' => 'Ms. Yevhenia Shynkarenko',
                'jabatan_diplomat' => 'CDA',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Center 3 Lt. 8, Jl. Jend. Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2155,
                'longitude' => 106.8188,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            KedutaanBesar::create($item);
        }
    }
}
