<?php

namespace Database\Seeders;

use App\Models\MisiAsingAsean;
use Illuminate\Database\Seeder;

class MisiAsingAseanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'au',
                'nama_negara' => 'Australia',
                'nama_misi_asing_asean_id' => 'Misi Australia untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of Australia to ASEAN',
                'format_undangan' => 'Head of Mission of Australia to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Tiffany Anne McDonald',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya Kav. 1-4',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2325270,
                'longitude' => 106.8344915,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'br',
                'nama_negara' => 'Brazil',
                'nama_misi_asing_asean_id' => 'Misi Republik Federasi Brasil untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of the Federative Republic of Brazil to ASEAN',
                'format_undangan' => 'Head of Mission of the Federative Republic of Brazil to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Henrique Archanjo Ferraro',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Wisma Mulia 2 Suite 2701, Jl. Jend. Gatot Subroto No. 40',
                'kelurahan' => 'Kuningan Barat',
                'kecamatan' => 'Mampang Prapatan',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12710',
                'website' => null,
                'latitude' => -6.2343189,
                'longitude' => 106.8220994,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ca',
                'nama_negara' => 'Kanada',
                'nama_misi_asing_asean_id' => 'Misi Kanada untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of Canada to ASEAN',
                'format_undangan' => 'Head of Mission of Canada to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Ambra Dickie',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'World Trade Centre Lt. 6, Jl. Jenderal Sudirman Kav. 29-31',
                'kelurahan' => 'Karet',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12920',
                'website' => null,
                'latitude' => -6.2151535,
                'longitude' => 106.8203787,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'cn',
                'nama_negara' => 'Republik Rakyat Tiongkok',
                'nama_misi_asing_asean_id' => 'Misi Republik Rakyat Tiongkok untuk ASEAN',
                'nama_misi_asing_asean_en' => "Mission of the People's Republic of China to ASEAN",
                'format_undangan' => "Head of Mission of the People's Republic of China to ASEAN",
                'nama_diplomat' => 'H.E. Mr. Wang Qing',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'The EAST Building Lt. 32, Jl. Lingkar Mega Kuningan Kav. E3.2 No. 1',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2294074,
                'longitude' => 106.8246989,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'eu',
                'nama_negara' => 'Uni Eropa',
                'nama_misi_asing_asean_id' => 'Misi Uni Eropa untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of the European Union to ASEAN',
                'format_undangan' => 'Head of Mission of the European Union to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Sujiro Seam',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Menara Astra Lt. 38, Jl. Jend. Sudirman Kav. 5-6',
                'kelurahan' => 'Karet Tengsin',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10220',
                'website' => null,
                'latitude' => -6.2072360,
                'longitude' => 106.8213540,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'in',
                'nama_negara' => 'India',
                'nama_misi_asing_asean_id' => 'Misi India untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of India to ASEAN',
                'format_undangan' => 'Head of Mission of India to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Srinivas Gotru',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan XII No. 3',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2316745,
                'longitude' => 106.8354932,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'jp',
                'nama_negara' => 'Jepang',
                'nama_misi_asing_asean_id' => 'Misi Jepang untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of Japan to ASEAN',
                'format_undangan' => 'Head of Mission of Japan to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Yonetani Koji',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. M.H. Thamrin No. 24',
                'kelurahan' => 'Gondangdia',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10350',
                'website' => null,
                'latitude' => -6.1934499,
                'longitude' => 106.8220881,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kr',
                'nama_negara' => 'Korea Selatan',
                'nama_misi_asing_asean_id' => 'Misi Republik Korea untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of the Republic of Korea to ASEAN',
                'format_undangan' => 'Head of Mission of the Republic of Korea to ASEAN',
                'nama_diplomat' => 'Kevin Kim',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Sentral Senayan II Lt. 23, Jl. Asia Afrika No. 8, Gelora Bung Karno',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => null,
                'latitude' => -6.2218186,
                'longitude' => 106.7990616,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'nz',
                'nama_negara' => 'Selandia Baru',
                'nama_misi_asing_asean_id' => 'Misi Selandia Baru untuk ASEAN',
                'nama_misi_asing_asean_en' => 'New Zealand Mission to ASEAN',
                'format_undangan' => 'Head of New Zealand Mission to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Joanna Anderson',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Sentral Senayan 2 Lt. 10, Jl. Asia Afrika No. 8, Gelora Bung Karno',
                'kelurahan' => 'Gelora',
                'kecamatan' => 'Tanah Abang',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10270',
                'website' => null,
                'latitude' => -6.2218186,
                'longitude' => 106.7990616,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ru',
                'nama_negara' => 'Rusia',
                'nama_misi_asing_asean_id' => 'Misi Federasi Rusia untuk ASEAN',
                'nama_misi_asing_asean_en' => 'Mission of the Russian Federation to ASEAN',
                'format_undangan' => 'Head of Mission of the Russian Federation to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Evgeny Zagaynov',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.R. Rasuna Said Kav. X-7 No. 1-2',
                'kelurahan' => 'Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12940',
                'website' => null,
                'latitude' => -6.2204788,
                'longitude' => 106.8316981,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'gb',
                'nama_negara' => 'Britania Raya',
                'nama_misi_asing_asean_id' => 'Misi Britania Raya untuk ASEAN',
                'nama_misi_asing_asean_en' => 'UK Mission to ASEAN',
                'format_undangan' => 'Head of UK Mission to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Helen Fazey',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Patra Kuningan Raya Blok L5-6',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2352584,
                'longitude' => 106.8332164,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'us',
                'nama_negara' => 'Amerika Serikat',
                'nama_misi_asing_asean_id' => 'Misi Amerika Serikat untuk ASEAN',
                'nama_misi_asing_asean_en' => 'United States Mission to ASEAN',
                'format_undangan' => 'Head of United States Mission to ASEAN',
                'nama_diplomat' => 'Kevin Kim',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Medan Merdeka Selatan No. 3-5',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10110',
                'website' => null,
                'latitude' => -6.1806580,
                'longitude' => 106.8302132,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            MisiAsingAsean::create($item);
        }
    }
}
