<?php

namespace Database\Seeders;

use App\Models\MisiPermanenNegaraAsean;
use Illuminate\Database\Seeder;

class MisiPermanenNegaraAseanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'bn',
                'nama_negara' => 'Brunei Darussalam',
                'nama_misi_resmi' => 'Permanent Mission of the Brunei Darussalam to ASEAN',
                'format_undangan' => 'Permanent Representative of Brunei Darussalam to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Latifah Zaini',
                'telepon_kantor' => '(62) 21 7279 8330',
                'email_kantor' => 'perwakilan.asean@mfa.gov.bn, BDPM@mfa.gov.bn',
                'alamat' => 'Jl. Ciasem IV No. 4, Kebayoran Baru, Jakarta Selatan 12180',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'kh',
                'nama_negara' => 'Cambodia',
                'nama_misi_resmi' => 'Permanent Mission of the Kingdom of Cambodia to ASEAN',
                'format_undangan' => 'Permanent Representative of the Kingdom of Cambodia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Noy Choumneanh',
                'telepon_kantor' => '(62) 21 2277 7931',
                'email_kantor' => 'camemb.asean@mfaic.gov.kh',
                'alamat' => 'Jl. Brawijaya II No. 12, Kebayoran Baru, Jakarta Selatan 12160',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'ph',
                'nama_negara' => 'Philippines',
                'nama_misi_resmi' => 'Permanent Mission of the Republic of Philippines to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of the Philippines to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Evangeline T. Ong Jimenez-Ducrocq',
                'telepon_kantor' => '(62) 21 7278 9030',
                'email_kantor' => 'jakartapm@gmail.com',
                'alamat' => 'Jl. Wijaya XVI No. 3/5, RW.07, Melawai, Kec. Kebayoran Baru, Kota Jakarta Selatan, DKI Jakarta 12160',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'id',
                'nama_negara' => 'Indonesia',
                'nama_misi_resmi' => 'Permanent Mission of the Republic of Indonesia to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of Indonesia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. M.I. Derry Aman',
                'telepon_kantor' => '(62) 2127510600',
                'email_kantor' => 'amb.pr.indonesia@gmail.com',
                'alamat' => 'Jl. Sisingamangaraja No. 73, Kebayoran Baru, Jakarta Selatan 12120',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'la',
                'nama_negara' => 'Laos',
                'nama_misi_resmi' => 'Permanent Mission of the Lao People\'s Democratic Republic to ASEAN',
                'format_undangan' => 'Permanent Representative of the Lao People\'s Democratic Republic to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Sitsangkhom Sisaketh',
                'telepon_kantor' => '(62) 21 720 1838/7279 4810',
                'email_kantor' => 'laoprjakarta@gmail.com',
                'alamat' => 'Jl. Pati Unus No. 12 Blok F/4, Kebayoran Baru, Jakarta Selatan',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'my',
                'nama_negara' => 'Malaysia',
                'nama_misi_resmi' => 'Permanent Mission of Malaysia to ASEAN',
                'format_undangan' => 'Permanent Representative of Malaysia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Sarah Al Bakri Devadason',
                'telepon_kantor' => '(62) 21 5290 5634',
                'email_kantor' => 'mwasean@kln.gov.my',
                'alamat' => 'JL. H. R. Rasuna Said No. 1-3, Kav. X/6, Kuningan, Jakarta Selatan 12950',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'mm',
                'nama_negara' => 'Myanmar',
                'nama_misi_resmi' => 'Permanent Mission of the Republic of the Union of Myanmar to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of the Union of Myanmar to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Aung Myo Myint',
                'telepon_kantor' => '(62) 22127097707',
                'email_kantor' => 'mmmission.asean@gmail.com',
                'alamat' => 'Jl. Prapanca IV, No.61, RT004/RW003, Kelurahan Pulo, Kecamatan Kebayoran Baru, Jakarta Selatan 12160',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'sg',
                'nama_negara' => 'Singapore',
                'nama_misi_resmi' => 'Permanent Mission of the Republic of Singapore to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of Singapore to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Gerard Ho',
                'telepon_kantor' => '(62) 21 2995 0400',
                'email_kantor' => 'singemb_jkt@mfa.sg',
                'alamat' => 'Jl. HR Rasuna Said Blok X/4 Kav No. 2, Kuningan, Jakarta 12950',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'th',
                'nama_negara' => 'Thailand',
                'nama_misi_resmi' => 'Permanent Mission of the Kingdom of Thailand to ASEAN',
                'format_undangan' => 'Permanent Representative of the Kingdom of Thailand to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Prinat Apirat',
                'telepon_kantor' => '(62) 21 572 5767',
                'email_kantor' => 'aseanjkm@thaijkm.org',
                'alamat' => 'Jl. Imam Bonjol No. 74, Menteng, Jakarta Pusat 10310',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'vn',
                'nama_negara' => 'Vietnam',
                'nama_misi_resmi' => 'Permanent Mission of the Socialist Republic of Viet Nam to ASEAN',
                'format_undangan' => 'Permanent Representative of the Socialist Republic of Viet Nam to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Dr. Ton Thi Ngoc Huong',
                'telepon_kantor' => '(62) 2131907255',
                'email_kantor' => 'pdvn.asean@mova.gov.vn',
                'alamat' => 'Jl. Pekalongan No. 9, Menteng, Jakarta Pusat 10310',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'tl',
                'nama_negara' => 'Timor Leste',
                'nama_misi_resmi' => 'Permanent Mission of the Democratic Republic of Timor-Leste to ASEAN',
                'format_undangan' => 'Permanent Representative of the Democratic Republic of Timor-Leste to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Natércia Cipriano Coelho da Silva',
                'telepon_kantor' => '(62) 21 2903 9513',
                'email_kantor' => 'paambtlasean@gmail.com',
                'alamat' => 'Atrium Mulia, 5th Floor, Suite 502 B, Jl. H.R. Rasuna Said Kav. B10-11, Kuningan, Jakarta Selatan 12910',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
        ];

        foreach ($data as $item) {
            MisiPermanenNegaraAsean::create($item);
        }
    }
}
