<?php

namespace Database\Seeders;

use App\Models\MisiAsingAsean;
use Illuminate\Database\Seeder;

class MisiAsingAseanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'au',
                'nama_negara' => 'Australia',
                'nama_misi_resmi' => 'Mission of Australia to ASEAN',
                'format_undangan' => 'Head of Mission of Australia to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Tiffany Anne McDonald',
                'telepon_kantor' => '62 21 25505 555',
                'email_kantor' => 'asean.mission@dfat.gov.au',
                'alamat' => 'Jl. Patra Kuningan Raya, Kav. 1-4, Jakarta Selatan 12950',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'br',
                'nama_negara' => 'Brazil',
                'nama_misi_resmi' => 'Mission of the Federative Republic of Brazil to ASEAN',
                'format_undangan' => 'Head of Mission of the Federative Republic of Brazil to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Henrique Archanjo Ferraro',
                'telepon_kantor' => '62-21 270 88 887',
                'email_kantor' => 'delbrasean@itamaraty.gov.br',
                'alamat' => 'Wisma Mulia 2, Suite 2701, Jl. Jend. Gatot Subroto No. 40, Jakarta - 12710',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'ca',
                'nama_negara' => 'Canada',
                'nama_misi_resmi' => 'Mission of Canada to ASEAN',
                'format_undangan' => 'Head of Mission of Canada to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Ambra Dickie',
                'telepon_kantor' => '62-21 2550 7800',
                'email_kantor' => 'ASEAN-ANASE@international.gc.ca',
                'alamat' => 'World Trade Centre (6th Fl.), Jl. Jenderal Sudirman Kav. 29-31, Jakarta - 12920',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'cn',
                'nama_negara' => 'China',
                'nama_misi_resmi' => 'Mission of the People\'s Republic of China to ASEAN',
                'format_undangan' => 'Head of Mission of the People\'s Republic of China to ASEAN',
                'nama_diplomat' => 'H.E. Wang Qing',
                'telepon_kantor' => '62-21 29527098 / 2952 7092',
                'email_kantor' => 'Website: http://asean.chinamission.org.cn/chn/',
                'alamat' => '32nd Floor, The EAST Building, Jl. Lingkar Mega Kuningan Kav. E3.2 No.1, Jakarta-12950',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'eu',
                'nama_negara' => 'European Union',
                'nama_misi_resmi' => 'Mission of the European Union to ASEAN',
                'format_undangan' => 'Head of Mission of the European Union to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Sujiro Seam',
                'telepon_kantor' => '62-21 2554 6290 / 2554 6200',
                'email_kantor' => 'DELEGATION-ASEAN@eeas.europa.eu',
                'alamat' => 'Menara Astra 38th Floor Jl. Jendral Sudirman Kav. 5-6, Jakarta-10220',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'in',
                'nama_negara' => 'India',
                'nama_misi_resmi' => 'Mission of India to ASEAN',
                'format_undangan' => 'Head of Mission of India to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Srinivas Gotru',
                'telepon_kantor' => '62-21-5221430',
                'email_kantor' => 'asean.jakarta@mea.gov.in; amb.asean@mea.gov.in',
                'alamat' => 'Jl. Patra Kuningan XII/3 Jakarta Selatan',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'jp',
                'nama_negara' => 'Japan',
                'nama_misi_resmi' => 'Mission of Japan to ASEAN',
                'format_undangan' => 'Head of Mission of Japan to ASEAN',
                'nama_diplomat' => 'H.E. Mr. Yonetani Koji',
                'telepon_kantor' => '62-21 3190 4901',
                'email_kantor' => null,
                'alamat' => 'Jl. M.H. Thamrin No. 24, Jakarta - 10350',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'kr',
                'nama_negara' => 'Republic of Korea (ROK)',
                'nama_misi_resmi' => 'Mission of the Republic of Korea to ASEAN',
                'format_undangan' => 'Head of Mission of the Republic of Korea to ASEAN',
                'nama_diplomat' => 'Vacant',
                'telepon_kantor' => '(62 21) 5795 1830',
                'email_kantor' => 'kor_asean@mofa.go.kr',
                'alamat' => 'Sentral Senayan II, 23rd Floor, Jl. Asia Afrika No. 8, Gelora Bung Karno, Jakarta Pusat - 10270',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'nz',
                'nama_negara' => 'New Zealand',
                'nama_misi_resmi' => 'New Zealand Mission to ASEAN',
                'format_undangan' => 'Head of New Zealand Mission to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Joanna Anderson',
                'telepon_kantor' => '62-21 2995 5800',
                'email_kantor' => 'nz.asean@mfat.govt.nz',
                'alamat' => 'Sentral Senayan 2, 10th floor, Jl. Asia Afrika No. 8, Gelora Bung Karno Jakarta - 10270',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'ru',
                'nama_negara' => 'Russia',
                'nama_misi_resmi' => 'Mission of the Russian Federation',
                'format_undangan' => 'Head of Mission of the Russian Federation',
                'nama_diplomat' => 'H.E. Mr. Evgeny Zagaynov',
                'telepon_kantor' => '62-21-5222912',
                'email_kantor' => 'asean@mid.ru',
                'alamat' => 'Jl. H.R. Rasuna Said, Kav.X-7, 1-2, Kuningan, Jakarta - 12940',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'gb',
                'nama_negara' => 'United Kingdom',
                'nama_misi_resmi' => 'UK Mission to ASEAN',
                'format_undangan' => 'Head of UK Mission to ASEAN',
                'nama_diplomat' => 'H.E. Ms. Helen Fazey',
                'telepon_kantor' => '62-21-23565334',
                'email_kantor' => 'UKMissiontoAsean@fco.gov.uk',
                'alamat' => 'Jl. Patra Kuningan Raya Blok L5-6, Jakarta - 12950',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Selatan',
                'kode_pos' => null,
            ],
            [
                'kode_negara' => 'us',
                'nama_negara' => 'United States of America',
                'nama_misi_resmi' => 'United States Mission to ASEAN',
                'format_undangan' => 'Head of United States Mission to ASEAN',
                'nama_diplomat' => 'Vacant',
                'telepon_kantor' => '62-21-50831000',
                'email_kantor' => 'USMissionASEAN@state.gov',
                'alamat' => 'Jl. Medan Merdeka Selatan 3-5, Jakarta - 10110',
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => 'Jakarta Pusat',
                'kode_pos' => null,
            ],
        ];

        foreach ($data as $item) {
            MisiAsingAsean::create($item);
        }
    }
}
