<?php

namespace Database\Seeders;

use App\Models\MisiPermanenAsean;
use Illuminate\Database\Seeder;

class MisiPermanenAseanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode_negara' => 'bn',
                'nama_negara' => 'Brunei Darussalam',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Brunei Darussalam untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Brunei Darussalam to ASEAN',
                'format_undangan' => 'Permanent Representative of Brunei Darussalam to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Latifah Zaini',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Ciasem IV No. 4',
                'kelurahan' => 'Rawa Barat',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12180',
                'website' => null,
                'latitude' => -6.2378464,
                'longitude' => 106.8122554,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'kh',
                'nama_negara' => 'Kamboja',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Kerajaan Kamboja untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Kingdom of Cambodia to ASEAN',
                'format_undangan' => 'Permanent Representative of the Kingdom of Cambodia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Noy Choumneanh',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Brawijaya II No. 12',
                'kelurahan' => 'Pulo',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12160',
                'website' => null,
                'latitude' => -6.2556636,
                'longitude' => 106.8043101,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'ph',
                'nama_negara' => 'Filipina',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Filipina untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Republic of the Philippines to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of the Philippines to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Evangeline T. Ong Jimenez-Ducrocq',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Wijaya XVI No. 3/5',
                'kelurahan' => 'Melawai',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12160',
                'website' => null,
                'latitude' => -6.2502821,
                'longitude' => 106.8031036,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'id',
                'nama_negara' => 'Indonesia',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Indonesia untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Republic of Indonesia to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of Indonesia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. M.I. Derry Aman',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Sisingamangaraja No. 73',
                'kelurahan' => 'Gunung',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12120',
                'website' => null,
                'latitude' => -6.2358203,
                'longitude' => 106.7981593,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'la',
                'nama_negara' => 'Laos',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Demokratik Rakyat Laos untuk ASEAN',
                'nama_misi_permanen_asean_en' => "Permanent Mission of the Lao People's Democratic Republic to ASEAN",
                'format_undangan' => "Permanent Representative of the Lao People's Democratic Republic to ASEAN",
                'nama_diplomat' => 'H.E. Amb. Sitsangkhom Sisaketh',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pati Unus No. 12 Blok F/4',
                'kelurahan' => 'Gunung',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12120',
                'website' => null,
                'latitude' => -6.2362693,
                'longitude' => 106.7958483,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'my',
                'nama_negara' => 'Malaysia',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Malaysia untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of Malaysia to ASEAN',
                'format_undangan' => 'Permanent Representative of Malaysia to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Sarah Al Bakri Devadason',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.R. Rasuna Said No. 1-3 Kav. X/6',
                'kelurahan' => 'Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2248284,
                'longitude' => 106.8325061,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'mm',
                'nama_negara' => 'Myanmar',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Persatuan Myanmar untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Republic of the Union of Myanmar to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of the Union of Myanmar to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Aung Myo Myint',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Prapanca IV No. 61',
                'kelurahan' => 'Pulo',
                'kecamatan' => 'Kebayoran Baru',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12160',
                'website' => null,
                'latitude' => -6.2520865,
                'longitude' => 106.8081358,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'sg',
                'nama_negara' => 'Singapura',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Singapura untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Republic of Singapore to ASEAN',
                'format_undangan' => 'Permanent Representative of the Republic of Singapore to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Gerard Ho',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. H.R. Rasuna Said Blok X/4 Kav. No. 2',
                'kelurahan' => 'Kuningan Timur',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12950',
                'website' => null,
                'latitude' => -6.2351758,
                'longitude' => 106.8299901,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'th',
                'nama_negara' => 'Thailand',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Kerajaan Thailand untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Kingdom of Thailand to ASEAN',
                'format_undangan' => 'Permanent Representative of the Kingdom of Thailand to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Prinat Apirat',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Imam Bonjol No. 74',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1966939,
                'longitude' => 106.8251508,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'vn',
                'nama_negara' => 'Vietnam',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Sosialis Vietnam untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Socialist Republic of Viet Nam to ASEAN',
                'format_undangan' => 'Permanent Representative of the Socialist Republic of Viet Nam to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Dr. Ton Thi Ngoc Huong',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Jl. Pekalongan No. 9',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'kota' => 'Jakarta Pusat',
                'kode_pos' => '10310',
                'website' => null,
                'latitude' => -6.1967706,
                'longitude' => 106.8268244,
                'is_active' => true,
            ],
            [
                'kode_negara' => 'tl',
                'nama_negara' => 'Timor Leste',
                'nama_misi_permanen_asean_id' => 'Misi Permanen Republik Demokratik Timor Leste untuk ASEAN',
                'nama_misi_permanen_asean_en' => 'Permanent Mission of the Democratic Republic of Timor-Leste to ASEAN',
                'format_undangan' => 'Permanent Representative of the Democratic Republic of Timor-Leste to ASEAN',
                'nama_diplomat' => 'H.E. Amb. Natércia Cipriano Coelho da Silva',
                'email_kantor' => null,
                'telepon_kantor' => null,
                'alamat' => 'Atrium Mulia Lt. 5 Suite 502 B, Jl. H.R. Rasuna Said Kav. B10-11',
                'kelurahan' => 'Kuningan',
                'kecamatan' => 'Setiabudi',
                'kota' => 'Jakarta Selatan',
                'kode_pos' => '12910',
                'website' => null,
                'latitude' => -6.2079432,
                'longitude' => 106.8294275,
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            MisiPermanenAsean::create($item);
        }
    }
}
